# Generated by Django 5.2.1 on 2026-09-17 15:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0050_bulkbillingpreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicDFN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, help_text='Operational project identifier/context for this DFN.', max_length=120)),
                ('code', models.CharField(db_index=True, help_text='DFN identifier, for example 06.', max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geographic DFN',
                'verbose_name_plural': 'Geographic DFNs',
                'ordering': ('project_id', 'code'),
                'indexes': [models.Index(fields=['project_id', 'active'], name='maps_dfn_project_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_id', 'code'), name='maps_unique_dfn_per_project')],
            },
        ),
        migrations.CreateModel(
            name='GeographicBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Operational Box / CTO identifier.', max_length=120)),
                ('box_type', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('official_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('official_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('validation_radius_m', models.PositiveIntegerField(default=30, help_text='Maximum distance in meters accepted for location verification.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dfn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='maps.geographicdfn')),
            ],
            options={
                'verbose_name': 'Geographic Box / CTO',
                'verbose_name_plural': 'Geographic Boxes / CTOs',
                'ordering': ('dfn', 'identifier'),
            },
        ),
        migrations.CreateModel(
            name='BoxLocationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('official_longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('captured_latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('captured_longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('gps_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distance_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validation_radius_m', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('verified', 'Verified'), ('outside_radius', 'Outside allowed radius'), ('insufficient_accuracy', 'Insufficient GPS accuracy')], db_index=True, max_length=30)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('billing_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_location_verifications', to='operaciones.sesionbilling')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_location_verifications', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_verifications', to='maps.geographicbox')),
            ],
            options={
                'verbose_name': 'Box Location Verification',
                'verbose_name_plural': 'Box Location Verifications',
                'ordering': ('-verified_at',),
                'indexes': [models.Index(fields=['billing_session', '-verified_at'], name='maps_bill_verify_idx'), models.Index(fields=['box', '-verified_at'], name='maps_box_verify_idx'), models.Index(fields=['technician', '-verified_at'], name='maps_tech_verify_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoxLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('old_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('new_latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('new_longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('source', models.CharField(choices=[('manual', 'Manual map'), ('import', 'Coordinate import'), ('other', 'Other')], default='manual', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_location_changes', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_history', to='maps.geographicbox')),
            ],
            options={
                'verbose_name': 'Box Location History',
                'verbose_name_plural': 'Box Location History',
                'ordering': ('-changed_at',),
                'indexes': [models.Index(fields=['box', '-changed_at'], name='maps_box_history_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillingBoxAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_box_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('billing_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_box_assignments', to='operaciones.sesionbilling')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_assignments', to='maps.geographicbox')),
            ],
            options={
                'verbose_name': 'Billing Box Assignment',
                'verbose_name_plural': 'Billing Box Assignments',
                'ordering': ('-assigned_at',),
                'indexes': [models.Index(fields=['billing_session', 'active'], name='maps_bill_box_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('billing_session', 'box'), name='maps_unique_billing_box_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='geographicbox',
            index=models.Index(fields=['dfn', 'active'], name='maps_box_dfn_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='geographicbox',
            constraint=models.UniqueConstraint(fields=('dfn', 'identifier'), name='maps_unique_box_per_dfn'),
        ),
    ]
