# Generated by Django 5.2.1 on 2026-09-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicbox',
            options={'ordering': ('identifier',), 'verbose_name': 'Geographic Box / CTO', 'verbose_name_plural': 'Geographic Boxes / CTOs'},
        ),
        migrations.AlterModelOptions(
            name='geographicdfn',
            options={'ordering': ('code',), 'verbose_name': 'Geographic DFN', 'verbose_name_plural': 'Geographic DFNs'},
        ),
        migrations.RemoveConstraint(
            model_name='geographicbox',
            name='maps_unique_box_per_dfn',
        ),
        migrations.RemoveConstraint(
            model_name='geographicdfn',
            name='maps_unique_dfn_per_project',
        ),
        migrations.RemoveIndex(
            model_name='geographicdfn',
            name='maps_dfn_project_active_idx',
        ),
        migrations.RemoveField(
            model_name='geographicdfn',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='geographicbox',
            name='dfn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='maps.geographicdfn'),
        ),
        migrations.AlterField(
            model_name='geographicbox',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Complete operational Project ID.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='geographicdfn',
            name='code',
            field=models.CharField(db_index=True, help_text='Complete DFN identifier, for example 0913RA_04.', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='geographicdfn',
            index=models.Index(fields=['active', 'code'], name='maps_dfn_active_code_idx'),
        ),
    ]
