# Generated by Django 5.2.1 on 2026-09-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_boxlocationhistory_new_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicbox',
            name='location_validation_enabled',
            field=models.BooleanField(default=True, help_text='Require technician location verification before starting work when this Box / CTO has an official location.'),
        ),
        migrations.AlterField(
            model_name='geographicbox',
            name='validation_radius_m',
            field=models.PositiveIntegerField(default=20, help_text='Maximum distance in meters accepted for location verification.'),
        ),
    ]
