# Generated by Django 5.2.1 on 2026-04-21 04:45

import django.db.models.deletion
import ombording.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ombording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('link_token', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Link Token')),
                ('link_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Link Expires At')),
                ('send_email_on_create', models.BooleanField(default=False, verbose_name='Send Email On Create')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_user', 'Pending User'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('rejected_partial', 'Rejected / Needs Correction'), ('approved', 'Approved'), ('completed', 'Completed'), ('expired', 'Expired')], default='draft', max_length=30, verbose_name='Status')),
                ('current_step', models.CharField(choices=[('initial', 'Initial Setup'), ('personal', 'Personal & Emergency'), ('identity', 'Identity & Work Authorization'), ('signature', 'Signature & Documents'), ('banking', 'Banking'), ('review', 'Review')], default='initial', max_length=30, verbose_name='Current Step')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('nationality', models.CharField(blank=True, max_length=120, verbose_name='Nationality')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Relationship')),
                ('has_ssn', models.BooleanField(blank=True, null=True, verbose_name='Has Social Security')),
                ('ssn_number', models.CharField(blank=True, max_length=50, verbose_name='Social Security Number')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Passport Number')),
                ('has_work_permit', models.BooleanField(blank=True, null=True, verbose_name='Has Work Permit')),
                ('has_driver_license', models.BooleanField(blank=True, null=True, verbose_name='Has Driver License')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='Bank Name')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='Account Type')),
                ('routing_number', models.CharField(blank=True, max_length=50, verbose_name='Routing Number')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('business_name', models.CharField(blank=True, max_length=150, verbose_name='Business Name')),
                ('w9_tax_classification', models.CharField(blank=True, max_length=50, verbose_name='W-9 Tax Classification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombordings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombordings_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ombordings', to='ombording.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Ombording',
                'verbose_name_plural': 'Ombordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmbordingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='Action')),
                ('detail', models.TextField(blank=True, verbose_name='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ombording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ombording.ombording', verbose_name='Ombording')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombording_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Ombording Audit Log',
                'verbose_name_plural': 'Ombording Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmbordingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_key', models.CharField(choices=[('contractor_agreement_base', 'Independent Contractor Agreement Base'), ('exhibit_base', 'Exhibit Base'), ('w9_base', 'W-9 Base'), ('passport_front', 'Passport Front'), ('passport_back', 'Passport Back'), ('address_proof', 'Address Proof'), ('ssn_front', 'SSN Front'), ('ssn_back', 'SSN Back'), ('work_permit_front', 'Work Permit Front'), ('work_permit_back', 'Work Permit Back'), ('driver_license_front', 'Driver License Front'), ('driver_license_back', 'Driver License Back'), ('contractor_agreement_filled', 'Independent Contractor Agreement Filled'), ('exhibit_filled', 'Exhibit Filled'), ('w9_filled', 'W-9 Filled')], max_length=60, verbose_name='Document Key')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('file', models.FileField(upload_to=ombording.models.ombording_document_upload_path, verbose_name='File')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Original Name')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Review Status')),
                ('review_comment', models.TextField(blank=True, verbose_name='Review Comment')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ombording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ombording.ombording', verbose_name='Ombording')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombording_documents_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombording_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Ombording Document',
                'verbose_name_plural': 'Ombording Documents',
                'ordering': ['document_key', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmbordingEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=80, verbose_name='Email Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ombording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='ombording.ombording', verbose_name='Ombording')),
            ],
            options={
                'verbose_name': 'Ombording Email Log',
                'verbose_name_plural': 'Ombording Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OmbordingSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(blank=True, max_length=150, verbose_name='Signature Name')),
                ('initials', models.CharField(blank=True, max_length=10, verbose_name='Initials')),
                ('signature_file', models.ImageField(blank=True, null=True, upload_to=ombording.models.ombording_signature_upload_path, verbose_name='Signature File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ombording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='ombording.ombording', verbose_name='Ombording')),
            ],
            options={
                'verbose_name': 'Ombording Signature',
                'verbose_name_plural': 'Ombording Signatures',
            },
        ),
        migrations.CreateModel(
            name='OmbordingFieldReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100, verbose_name='Field Key')),
                ('field_label', models.CharField(max_length=200, verbose_name='Field Label')),
                ('step', models.CharField(choices=[('initial', 'Initial Setup'), ('personal', 'Personal & Emergency'), ('identity', 'Identity & Work Authorization'), ('signature', 'Signature & Documents'), ('banking', 'Banking'), ('review', 'Review')], max_length=30, verbose_name='Step')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Review Status')),
                ('review_comment', models.TextField(blank=True, verbose_name='Review Comment')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ombording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='ombording.ombording', verbose_name='Ombording')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombording_field_reviews_done', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Ombording Field Review',
                'verbose_name_plural': 'Ombording Field Reviews',
                'ordering': ['step', 'field_label'],
                'unique_together': {('ombording', 'field_key')},
            },
        ),
    ]
