# Generated by Django 5.2.1 on 2026-04-21 05:27

import ombording.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombording', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombordingdocument',
            name='document_key',
            field=models.CharField(choices=[('contractor_agreement_base', 'Independent Contractor Agreement Base'), ('exhibit_base', 'Exhibit Base'), ('w9_base', 'W-9 Base'), ('passport_front', 'Passport Front'), ('passport_back', 'Passport Back'), ('address_proof', 'Address Proof'), ('ssn_front', 'Social Security Front'), ('ssn_back', 'Social Security Back'), ('work_permit_front', 'Work Permit Front'), ('work_permit_back', 'Work Permit Back'), ('driver_license_front', 'Driver License Front'), ('driver_license_back', 'Driver License Back'), ('contractor_agreement_filled', 'Independent Contractor Agreement Filled'), ('exhibit_filled', 'Exhibit Filled'), ('w9_filled', 'W-9 Filled')], max_length=60, verbose_name='Document Key'),
        ),
        migrations.AlterField(
            model_name='ombordingdocument',
            name='file',
            field=models.FileField(max_length=1024, storage=storages.backends.s3.S3Storage(), upload_to=ombording.models.ombording_document_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='ombordingsignature',
            name='signature_file',
            field=models.ImageField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to=ombording.models.ombording_signature_upload_path, verbose_name='Signature File'),
        ),
    ]
