# Generated by Django 5.2.1 on 2026-04-21 06:19

import django.db.models.deletion
import ombording.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombording', '0002_alter_ombordingdocument_document_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ombordingfieldreview',
            options={'ordering': ['field_label'], 'verbose_name': 'Ombording Field Review', 'verbose_name_plural': 'Ombording Field Reviews'},
        ),
        migrations.CreateModel(
            name='OmbordingTempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('file', models.FileField(max_length=1024, storage=storages.backends.s3.S3Storage(), upload_to=ombording.models.ombording_temp_upload_path, verbose_name='File')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombording_temp_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ombording Temp Upload',
                'verbose_name_plural': 'Ombording Temp Uploads',
                'ordering': ['-created_at'],
                'unique_together': {('session_key', 'field_name')},
            },
        ),
    ]
