# Generated by Django 5.2.1 on 2026-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombording', '0003_alter_ombordingfieldreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombording',
            name='documents_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Documents Generated At'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='entry_mode',
            field=models.CharField(choices=[('internal', 'Internal'), ('public_link', 'Public Link')], default='internal', max_length=20, verbose_name='Entry Mode'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='worker_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Worker Signed At'),
        ),
    ]
