# Generated by Django 5.2.1 on 2026-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombording', '0004_ombording_documents_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombording',
            name='ein_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Employer Identification Number'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='w9_account_numbers',
            field=models.CharField(blank=True, max_length=255, verbose_name='W-9 Account Numbers'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='w9_exempt_payee_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='W-9 Exempt Payee Code'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='w9_fatca_exemption_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='W-9 FATCA Exemption Code'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='w9_llc_classification',
            field=models.CharField(blank=True, max_length=1, verbose_name='W-9 LLC Classification'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='w9_other_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='W-9 Other Text'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='w9_part3b_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='W-9 Part 3b Required'),
        ),
    ]
