# Generated by Django 5.2.1 on 2026-04-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombording', '0005_ombording_ein_number_ombording_w9_account_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ombording',
            name='address',
        ),
        migrations.AddField(
            model_name='ombording',
            name='apt_suite',
            field=models.CharField(blank=True, max_length=120, verbose_name='Apt / Suite'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='state',
            field=models.CharField(blank=True, max_length=120, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='ombording',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='ZIP Code'),
        ),
    ]
