# Generated by Django 5.2.1 on 2026-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombording', '0007_add_public_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ombording',
            name='rejection_note',
            field=models.TextField(blank=True, verbose_name='Rejection Note'),
        ),
        migrations.AlterField(
            model_name='ombording',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_user', 'Pending User'), ('in_correction', 'In Correction'), ('in_review', 'Pending Review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('expired', 'Expired')], default='draft', max_length=30, verbose_name='Status'),
        ),
    ]
