# Generated by Django 5.2.1 on 2026-06-01 21:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Código interno de la API. Ej: mobile_billing', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Nombre visible. Ej: Mobile Billing API', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Descripción breve del uso de esta API.')),
                ('is_enabled', models.BooleanField(default=False, help_text='Indica si esta API está activa.')),
                ('only_superusers', models.BooleanField(default=False, help_text='Si está activo, solo superusers pueden usar esta API.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_features_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Feature',
                'verbose_name_plural': 'API Features',
                'ordering': ['code'],
            },
        ),
    ]
