# Generated by Django 5.2.1 on 2026-07-17 17:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_submissions', '0002_alter_clientsubmissionbatch_execution_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteBrowserSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('active', 'Active'), ('processing_action', 'Processing action'), ('waiting_for_user', 'Waiting for user'), ('verification_passed', 'Verification passed'), ('submission_confirmed', 'Submission confirmed'), ('restart_requested', 'Restart requested'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('closed', 'Closed'), ('failed', 'Failed')], db_index=True, default='starting', max_length=40)),
                ('captcha_status', models.CharField(choices=[('unknown', 'Unknown'), ('challenge_active', 'Challenge active'), ('dynamic_challenge', 'Dynamic challenge'), ('new_challenge_detected', 'New challenge detected'), ('verification_processing', 'Verification processing'), ('verification_passed', 'Verification passed'), ('verification_failed', 'Verification failed'), ('not_visible', 'Not visible')], db_index=True, default='unknown', max_length=40)),
                ('stage', models.CharField(blank=True, db_index=True, default='', help_text='Automation stage where the remote session started. Examples: form_load, before_form_fill, after_submit.', max_length=100)),
                ('worker_identifier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('browser_session_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('viewport_width', models.PositiveIntegerField(default=1440)),
                ('viewport_height', models.PositiveIntegerField(default=1100)),
                ('device_scale_factor', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='client_submission_remote/screenshots/%Y/%m/')),
                ('screenshot_version', models.PositiveBigIntegerField(default=0)),
                ('screenshot_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screenshot_height', models.PositiveIntegerField(blank=True, null=True)),
                ('screenshot_captured_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('screenshot_error', models.TextField(blank=True, default='')),
                ('browser_url', models.URLField(blank=True, default='', max_length=2000)),
                ('browser_title', models.CharField(blank=True, default='', max_length=1000)),
                ('page_scroll_x', models.IntegerField(default=0)),
                ('page_scroll_y', models.IntegerField(default=0)),
                ('page_document_width', models.PositiveIntegerField(blank=True, null=True)),
                ('page_document_height', models.PositiveIntegerField(blank=True, null=True)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('max_rounds', models.PositiveIntegerField(default=10)),
                ('action_count', models.PositiveIntegerField(default=0)),
                ('last_action_type', models.CharField(blank=True, default='', max_length=50)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, default='', max_length=100)),
                ('controller_acquired_at', models.DateTimeField(blank=True, null=True)),
                ('controller_last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_worker_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_browser_sessions', to='client_submissions.clientsubmissionattempt')),
                ('controller_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_remote_browser_sessions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_browser_sessions', to='client_submissions.clientsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteBrowserAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('click', 'Click'), ('double_click', 'Double click'), ('multi_click', 'Multiple clicks'), ('scroll', 'Scroll'), ('refresh_screenshot', 'Refresh screenshot'), ('verify', 'Verify CAPTCHA'), ('continue', 'Continue verification'), ('restart', 'Restart CAPTCHA'), ('cancel', 'Cancel submission')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Validated action data such as click coordinates or scroll distance.')),
                ('screenshot_version', models.PositiveBigIntegerField(default=0, help_text='Screenshot version visible to the user when the action was requested.')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_browser_actions_requested', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='client_submission_remote.remotebrowsersession')),
            ],
            options={
                'ordering': ['requested_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='remotebrowsersession',
            index=models.Index(fields=['submission', 'status'], name='csr_session_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='remotebrowsersession',
            index=models.Index(fields=['status', 'expires_at'], name='csr_session_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='remotebrowsersession',
            index=models.Index(fields=['worker_identifier', 'status'], name='csr_session_worker_idx'),
        ),
        migrations.AddConstraint(
            model_name='remotebrowsersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['starting', 'active', 'processing_action', 'waiting_for_user', 'restart_requested'])), fields=('submission',), name='csr_one_open_session_per_sub'),
        ),
        migrations.AddIndex(
            model_name='remotebrowseraction',
            index=models.Index(fields=['session', 'status', 'requested_at'], name='csr_action_sess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='remotebrowseraction',
            index=models.Index(fields=['status', 'requested_at'], name='csr_action_status_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='remotebrowseraction',
            constraint=models.CheckConstraint(condition=models.Q(('screenshot_version__gte', 0)), name='csr_action_screen_ver_gte_0'),
        ),
    ]
