# Generated by Django 5.2.1 on 2026-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_submission_remote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotebrowsersession',
            name='screenshot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='client_submission_remote/screenshots/%Y/%m/'),
        ),
    ]
