# Generated by Django 5.2.1 on 2026-07-14 04:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0043_alter_requirementlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('dfn_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('access_point_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending_client_submission', 'Pending client submission'), ('preparing_client_submission', 'Preparing client submission'), ('awaiting_verification', 'Awaiting verification'), ('submitting_to_client', 'Submitting to client'), ('awaiting_email_confirmation', 'Awaiting email confirmation'), ('sent_to_client', 'Sent to client'), ('dry_run_completed', 'Dry Run completed'), ('client_submission_failed', 'Client submission failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_client_submission', max_length=50)),
                ('sequence_number', models.PositiveIntegerField(default=0, help_text='Processing order within the batch.')),
                ('form_payload', models.JSONField(blank=True, default=dict, help_text='Resolved form data for this project. This is a snapshot of what will be submitted.')),
                ('billing_codes_snapshot', models.JSONField(blank=True, default=list, help_text='Snapshot of Billing items and quantities used to build the Smartsheet form.')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='client_submissions/zips/%Y/%m/')),
                ('zip_source_url', models.URLField(blank=True, default='', help_text='Original URL of the ZIP when the file is stored outside Django default storage.', max_length=2000)),
                ('zip_filename', models.CharField(blank=True, default='', max_length=500)),
                ('zip_size', models.BigIntegerField(blank=True, null=True)),
                ('zip_available', models.BooleanField(db_index=True, default=False)),
                ('validation_ok', models.BooleanField(db_index=True, default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('form_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('form_completed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_required_at', models.DateTimeField(blank=True, null=True)),
                ('verification_completed_at', models.DateTimeField(blank=True, null=True)),
                ('submit_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('browser_confirmation_at', models.DateTimeField(blank=True, null=True)),
                ('email_confirmation_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('browser_confirmation_received', models.BooleanField(db_index=True, default=False)),
                ('email_confirmation_received', models.BooleanField(db_index=True, default=False)),
                ('confirmation_reference', models.CharField(blank=True, default='', max_length=500)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('browser_session_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('browser_state', models.JSONField(blank=True, default=dict, help_text='Non-sensitive automation state needed to continue the current submission.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_submissions', to='operaciones.sesionbilling')),
            ],
            options={
                'ordering': ['sequence_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientSubmissionBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='Optional internal name for this submission batch.', max_length=200)),
                ('form_url', models.URLField(default='https://app.smartsheet.com/b/form/a45ea2b5dbce49d2b5fcd8177d5be815', max_length=1000)),
                ('execution_mode', models.CharField(choices=[('dry_run', 'Dry Run'), ('live', 'Live submission')], db_index=True, default='dry_run', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending to start'), ('running', 'Processing'), ('awaiting_verification', 'Awaiting verification'), ('paused', 'Paused'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=40)),
                ('submitted_by_email', models.EmailField(default='l.suarez@hyperlink-networks.com', max_length=254)),
                ('send_copy_of_responses', models.BooleanField(default=True)),
                ('copy_email', models.EmailField(default='l.suarez@hyperlink-networks.com', max_length=254)),
                ('additional_copy_emails', models.JSONField(blank=True, default=list, help_text='Additional internal recipients. These are not necessarily entered in the Smartsheet form.')),
                ('is_subcontractor', models.BooleanField(default=True)),
                ('subcontractor_name', models.CharField(default='Hyperlink', max_length=255)),
                ('production_completed_date', models.DateField(blank=True, null=True)),
                ('market', models.CharField(blank=True, default='', max_length=255)),
                ('fiber_placed', models.BooleanField(default=False)),
                ('splicing', models.BooleanField(default=False)),
                ('testing', models.BooleanField(default=False)),
                ('aerial_case', models.BooleanField(default=False)),
                ('re_entry', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('worker_identifier', models.CharField(blank=True, default='', help_text='Identifier of the worker currently processing the batch.', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_submission_batches_created', to=settings.AUTH_USER_MODEL)),
                ('current_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_submissions.clientsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientsubmission',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='client_submissions.clientsubmissionbatch'),
        ),
        migrations.CreateModel(
            name='ClientSubmissionConfirmation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('email', 'Email'), ('browser', 'Browser'), ('manual', 'Manual')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='External identifier such as an email message ID.', max_length=500)),
                ('sender', models.CharField(blank=True, default='', max_length=500)),
                ('recipient', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('project_id_detected', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('dfn_name_detected', models.CharField(blank=True, default='', max_length=255)),
                ('access_point_id_detected', models.CharField(blank=True, default='', max_length=255)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='client_submissions.clientsubmission')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSubmissionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client_submissions.clientsubmissionbatch')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client_submissions.clientsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('result', models.CharField(choices=[('started', 'Started'), ('form_completed', 'Form completed'), ('awaiting_verification', 'Awaiting verification'), ('browser_confirmed', 'Browser confirmed'), ('dry_run_completed', 'Dry Run completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='started', max_length=40)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('form_url', models.URLField(blank=True, default='', max_length=1000)),
                ('form_payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('browser_url', models.URLField(blank=True, default='', max_length=2000)),
                ('browser_title', models.CharField(blank=True, default='', max_length=1000)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='client_submissions/screenshots/%Y/%m/')),
                ('screenshot_url', models.URLField(blank=True, default='', max_length=2000)),
                ('page_html_snapshot', models.TextField(blank=True, default='', help_text='Optional sanitized HTML fragment for troubleshooting. Avoid storing secrets or unnecessary personal data.')),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('ai_used', models.BooleanField(default=False)),
                ('ai_result', models.JSONField(blank=True, default=dict, help_text='AI-assisted interpretation of form structure or automation errors. AI is not used to analyze project photos.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='client_submissions.clientsubmission')),
            ],
            options={
                'ordering': ['-attempt_number', '-created_at'],
                'indexes': [models.Index(fields=['submission', 'result'], name='cs_attempt_sub_result_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'attempt_number'), name='cs_unique_attempt_number')],
            },
        ),
        migrations.AddIndex(
            model_name='clientsubmissionbatch',
            index=models.Index(fields=['status', 'created_at'], name='cs_batch_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubmissionbatch',
            index=models.Index(fields=['execution_mode', 'status'], name='cs_batch_mode_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubmission',
            index=models.Index(fields=['batch', 'status', 'sequence_number'], name='cs_sub_batch_status_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubmission',
            index=models.Index(fields=['status', 'created_at'], name='cs_sub_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubmission',
            index=models.Index(fields=['project_id', 'status'], name='cs_sub_project_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientsubmission',
            constraint=models.UniqueConstraint(fields=('batch', 'billing_session'), name='cs_unique_billing_per_batch'),
        ),
        migrations.AddIndex(
            model_name='clientsubmissionconfirmation',
            index=models.Index(fields=['submission', 'source'], name='cs_confirm_sub_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientsubmissionconfirmation',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='cs_unique_confirmation_external_id'),
        ),
        migrations.AddIndex(
            model_name='clientsubmissionevent',
            index=models.Index(fields=['batch', 'created_at'], name='cs_event_batch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubmissionevent',
            index=models.Index(fields=['submission', 'created_at'], name='cs_event_sub_created_idx'),
        ),
    ]
