# Generated by Django 5.2.1 on 2026-07-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubmissionbatch',
            name='execution_mode',
            field=models.CharField(choices=[('dry_run', 'Dry Run'), ('live', 'Live submission')], db_index=True, default='live', max_length=20),
        ),
    ]
