# Generated by Django 5.2.1 on 2026-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_submissions', '0002_alter_clientsubmissionbatch_execution_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubmissionattempt',
            name='screenshot',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='client_submissions/screenshots/%Y/%m/'),
        ),
    ]
