# Generated by Django 5.2.1 on 2025-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionTecnico',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID de Producción')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('mes', models.CharField(max_length=20, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Producción Técnica',
                'verbose_name_plural': 'Producciones Técnicas',
            },
        ),
    ]
