# Generated by Django 5.2.1 on 2025-06-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producciontecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones_dashboard', to='tecnicos.tecnico'),
        ),
    ]
