# Generated by Django 5.2.1 on 2026-01-30 23:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255, verbose_name='Project Name')),
                ('rod_length', models.CharField(blank=True, default='', help_text='Example: 10 ft, 3 m, etc.', max_length=50, verbose_name='Rod Length')),
                ('driller_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Driller Name')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Vendor Name')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('base_template_docx', models.FileField(blank=True, help_text='Upload the original client DOCX. We will fill it without changing its formatting.', null=True, upload_to='borelogs/templates/%Y/%m/', verbose_name='Upload Bore (Client DOCX Template)')),
                ('cell_map', models.JSONField(blank=True, help_text='Generated after scanning the template once.', null=True, verbose_name='Cell Map (Rod -> Cell Coordinates)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borelogs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bore Log',
                'verbose_name_plural': 'Bore Logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BoreLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod_number', models.PositiveSmallIntegerField(db_index=True, help_text='Sequential rod number (usually 1..50).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Rod #')),
                ('depth', models.CharField(blank=True, default='', max_length=50, verbose_name='Depth')),
                ('pitch', models.CharField(blank=True, default='', max_length=50, verbose_name='Pitch')),
                ('station', models.CharField(blank=True, default='', max_length=50, verbose_name='Station')),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram')], db_index=True, default='web', max_length=20, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('borelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='borelogs.borelog', verbose_name='Bore Log')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borelog_entries', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bore Log Entry',
                'verbose_name_plural': 'Bore Log Entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['borelog', 'rod_number', '-created_at'], name='borelogs_bo_borelog_38716a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoreLogRodValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod_number', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Rod #')),
                ('depth', models.CharField(blank=True, default='', max_length=50, verbose_name='Depth')),
                ('pitch', models.CharField(blank=True, default='', max_length=50, verbose_name='Pitch')),
                ('station', models.CharField(blank=True, default='', max_length=50, verbose_name='Station')),
                ('last_source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram')], default='web', max_length=20, verbose_name='Last Source')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('borelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rod_values', to='borelogs.borelog', verbose_name='Bore Log')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borelog_rodvalues_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Bore Log Rod Value',
                'verbose_name_plural': 'Bore Log Rod Values',
                'ordering': ('rod_number',),
                'unique_together': {('borelog', 'rod_number')},
            },
        ),
    ]
