# Generated by Django 5.2.1 on 2026-01-31 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borelogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoreLogTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod_cell_map', models.JSONField(blank=True, null=True, verbose_name='Rod Cell Map')),
                ('header_cell_map', models.JSONField(blank=True, null=True, verbose_name='Header Cell Map')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Bore Log Template Config',
                'verbose_name_plural': 'Bore Log Template Config',
            },
        ),
        migrations.RemoveIndex(
            model_name='borelogentry',
            name='borelogs_bo_borelog_38716a_idx',
        ),
        migrations.RemoveField(
            model_name='borelog',
            name='base_template_docx',
        ),
        migrations.RemoveField(
            model_name='borelog',
            name='cell_map',
        ),
        migrations.AlterField(
            model_name='borelog',
            name='rod_length',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rod Length'),
        ),
        migrations.AlterField(
            model_name='borelogentry',
            name='rod_number',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Rod #'),
        ),
    ]
