# Generated by Django 5.2.1 on 2026-02-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borelogs', '0002_borelogtemplateconfig_and_more'),
        ('operaciones', '0028_sesionbilling_finance_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borelog',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borelogs', to='operaciones.sesionbilling', verbose_name='Billing Session'),
        ),
    ]
