# Generated by Django 5.2.1 on 2026-01-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('make', models.CharField(blank=True, default='', max_length=80)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plate', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('plate_state', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('vin', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('serials', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('odometer_unit', models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], db_index=True, default='mi', max_length=2)),
                ('initial_odometer', models.PositiveIntegerField(default=0)),
                ('last_odometer', models.PositiveIntegerField(default=0)),
                ('last_odometer_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_active', 'name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='fleet_vehic_is_acti_ee37a1_idx'), models.Index(fields=['fleet_id'], name='fleet_vehic_fleet_i_352a45_idx'), models.Index(fields=['vin'], name='fleet_vehic_vin_03441a_idx'), models.Index(fields=['plate', 'plate_state'], name='fleet_vehic_plate_fb04d3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('vin',), name='uniq_vehicle_vin_nonempty'), models.UniqueConstraint(condition=models.Q(models.Q(('plate', ''), _negated=True), models.Q(('plate_state', ''), _negated=True)), fields=('plate', 'plate_state'), name='uniq_vehicle_plate_state_nonempty')],
            },
        ),
    ]
