# Generated by Django 5.2.1 on 2026-04-04 19:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=32, unique=True)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, help_text='Odometer (miles)')),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision_tecnica', models.DateField(blank=True, null=True)),
                ('fecha_permiso_circulacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Interval (miles)', null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Interval (days)', null=True)),
                ('alert_before_km', models.PositiveIntegerField(blank=True, help_text='Alert before (miles)', null=True)),
                ('alert_before_days', models.PositiveIntegerField(blank=True, help_text='Alert before (days)', null=True)),
                ('alert_before_km_steps', models.CharField(blank=True, default='', help_text='CSV miles steps: e.g. 1000,500,100', max_length=120)),
                ('alert_before_days_steps', models.CharField(blank=True, default='', help_text='CSV days steps: e.g. 30,10,5', max_length=120)),
                ('notify_on_overdue', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='gray', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOdometerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('odometer', models.PositiveIntegerField(help_text='Odometer (miles)')),
                ('prev_odometer', models.PositiveIntegerField(default=0, help_text='Previous odometer (miles)')),
                ('source', models.CharField(default='manual', max_length=64)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_events', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.PositiveIntegerField(default=0, editable=False)),
                ('service_type', models.CharField(choices=[('combustible', 'Fuel'), ('aceite', 'Oil change'), ('neumaticos', 'Tires'), ('revision_tecnica', 'Technical inspection'), ('permiso_circulacion', 'Vehicle permit'), ('otro', 'Other')], default='otro', max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('service_date', models.DateField(default=django.utils.timezone.localdate)),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('kilometraje_declarado', models.PositiveIntegerField(blank=True, help_text='Odometer (miles)', null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_due_km', models.PositiveIntegerField(blank=True, help_text='Next due (miles)', null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleet.vehicle')),
                ('service_type_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicleservicetype')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehiclestatus'),
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle',), name='uq_vehicle_one_active_assignment')],
            },
        ),
    ]
