# Generated by Django 5.2.1 on 2026-04-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('include_assigned_driver', models.BooleanField(default=True)),
                ('extra_emails_to', models.TextField(blank=True, default='')),
                ('extra_emails_cc', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_cfg', to='fleet.vehicle')),
            ],
        ),
    ]
