# Generated by Django 5.2.1 on 2026-01-10 00:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_fix_real_consumption_date_nullable'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_active', '-created_at', '-id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='uniq_vehicle_vin_nonempty',
        ),
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='uniq_vehicle_plate_state_nonempty',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='fleet_vehic_is_acti_ee37a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='fleet_vehic_plate_fb04d3_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_odometer_updated_at',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer_unit',
            field=models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='fleet_vehic_is_acti_007c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['name'], name='fleet_vehic_name_0710c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('plate_state', 'plate'), name='uniq_vehicle_plate_state_plate'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments_as_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='facturacion.proyecto'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments_as_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleet.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', 'is_active'], name='fleet_vehic_vehicle_4a38f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['project', 'is_active'], name='fleet_vehic_project_4c0a12_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['assigned_to', 'is_active'], name='fleet_vehic_assigne_0175d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle',), name='uniq_active_assignment_per_vehicle'),
        ),
    ]
