# fleet/migrations/0003_ensure_vehicleservicetype_table.py
from django.db import migrations

POSTGRES_SQL = """
CREATE TABLE IF NOT EXISTS fleet_vehicleservicetype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    interval_km INTEGER NULL,
    interval_days INTEGER NULL,

    alert_before_km INTEGER NULL,
    alert_before_days INTEGER NULL,

    alert_before_km_steps VARCHAR(120) NOT NULL DEFAULT '',
    alert_before_days_steps VARCHAR(120) NOT NULL DEFAULT '',

    notify_on_overdue BOOLEAN NOT NULL DEFAULT FALSE
);
"""

SQLITE_SQL = """
CREATE TABLE IF NOT EXISTS fleet_vehicleservicetype (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT 1,

    interval_km INTEGER NULL,
    interval_days INTEGER NULL,

    alert_before_km INTEGER NULL,
    alert_before_days INTEGER NULL,

    alert_before_km_steps VARCHAR(120) NOT NULL DEFAULT '',
    alert_before_days_steps VARCHAR(120) NOT NULL DEFAULT '',

    notify_on_overdue BOOLEAN NOT NULL DEFAULT 0
);
"""


def create_table_if_missing(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(POSTGRES_SQL)
    elif vendor == "sqlite":
        schema_editor.execute(SQLITE_SQL)
    else:
        # No romper deploy si algún día cambias motor
        return


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_vehiclenotificationconfig"),
    ]

    operations = [
        migrations.RunPython(create_table_if_missing, migrations.RunPython.noop),
    ]
