# Generated by Django 5.2.1 on 2026-01-10 00:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fleet.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_fix_real_consumption_date_nullable'),
        ('fleet', '0002_vehicleassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOdometerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('odometer', models.PositiveIntegerField()),
                ('delta_since_last', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('odometer_photo', models.ImageField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to=fleet.models.upload_to_odometer_photo, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_logs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proyecto')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_logs', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['vehicle', 'date'], name='fleet_vehic_vehicle_900662_idx'), models.Index(fields=['vehicle', 'odometer'], name='fleet_vehic_vehicle_308916_idx')],
            },
        ),
    ]
