# Generated by Django 5.2.1 on 2026-04-07 01:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_cartolamovimiento_service_date_and_more'),
        ('fleet', '0002_vehiclenotificationconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleodometerevent',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='odometer_photo',
            field=models.FileField(blank=True, null=True, upload_to='fleet/odometer_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proyecto'),
        ),
    ]
