# Generated by Django 5.2.1 on 2026-04-09

from __future__ import annotations

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0015_fix_real_consumption_date_nullable"),
        ("fleet", "0003_vehicleodometerlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ==========================================================
        # 0) Borrar Fleet antiguo (solo tablas de fleet)
        # ==========================================================
        migrations.DeleteModel(name="VehicleOdometerLog"),
        migrations.DeleteModel(name="VehicleAssignment"),
        migrations.DeleteModel(name="Vehicle"),
        # ==========================================================
        # 1) Sequence
        # ==========================================================
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        # ==========================================================
        # 2) VehicleStatus
        # ==========================================================
        migrations.CreateModel(
            name="VehicleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(default="gray", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        # ==========================================================
        # 3) Vehicle (nuevo)
        # ==========================================================
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patente", models.CharField(max_length=32, unique=True)),
                (
                    "vin",
                    models.CharField(
                        max_length=17, unique=True, db_index=True, null=True, blank=True
                    ),
                ),
                ("marca", models.CharField(blank=True, default="", max_length=80)),
                ("modelo", models.CharField(blank=True, default="", max_length=80)),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "kilometraje_actual",
                    models.PositiveIntegerField(
                        default=0, help_text="Odometer (miles)"
                    ),
                ),
                ("last_movement_at", models.DateTimeField(blank=True, null=True)),
                ("fecha_revision_tecnica", models.DateField(blank=True, null=True)),
                ("fecha_permiso_circulacion", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.vehiclestatus",
                    ),
                ),
            ],
            options={"ordering": ["patente"]},
        ),
        # ==========================================================
        # 4) VehicleAssignment (nuevo)
        # ==========================================================
        migrations.CreateModel(
            name="VehicleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={"ordering": ["-assigned_at"]},
        ),
        migrations.AddConstraint(
            model_name="vehicleassignment",
            constraint=models.UniqueConstraint(
                fields=("vehicle",),
                condition=models.Q(("is_active", True)),
                name="uq_vehicle_one_active_assignment",
            ),
        ),
        # ==========================================================
        # 5) VehicleOdometerEvent (nuevo)
        # ==========================================================
        migrations.CreateModel(
            name="VehicleOdometerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "odometer_photo",
                    models.FileField(
                        upload_to="fleet/odometer_photos/",
                        storage=storages.backends.s3.S3Storage(),
                        blank=True,
                        null=True,
                        max_length=1024,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("odometer", models.PositiveIntegerField(help_text="Odometer (miles)")),
                (
                    "prev_odometer",
                    models.PositiveIntegerField(
                        default=0, help_text="Previous odometer (miles)"
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=64)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facturacion.proyecto",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odometer_events",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={"ordering": ["-event_at", "-id"]},
        ),
        # ==========================================================
        # 6) VehicleServiceType (nuevo)  <-- PRIMERO
        # ==========================================================
        migrations.CreateModel(
            name="VehicleServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "interval_km",
                    models.PositiveIntegerField(
                        null=True, blank=True, help_text="Interval (miles)"
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        null=True, blank=True, help_text="Interval (days)"
                    ),
                ),
                (
                    "alert_before_km",
                    models.PositiveIntegerField(
                        null=True, blank=True, help_text="Alert before (miles)"
                    ),
                ),
                (
                    "alert_before_days",
                    models.PositiveIntegerField(
                        null=True, blank=True, help_text="Alert before (days)"
                    ),
                ),
                (
                    "alert_before_km_steps",
                    models.CharField(
                        max_length=120,
                        blank=True,
                        default="",
                        help_text="CSV miles steps: e.g. 1000,500,100",
                    ),
                ),
                (
                    "alert_before_days_steps",
                    models.CharField(
                        max_length=120,
                        blank=True,
                        default="",
                        help_text="CSV days steps: e.g. 30,10,5",
                    ),
                ),
                ("notify_on_overdue", models.BooleanField(default=False)),
            ],
            options={"ordering": ["name"]},
        ),
        # ==========================================================
        # 7) VehicleService (nuevo)  <-- DESPUÉS
        # ==========================================================
        migrations.CreateModel(
            name="VehicleService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_code",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "service_type",
                    models.CharField(
                        max_length=40,
                        default="otro",
                        choices=[
                            ("combustible", "Fuel"),
                            ("aceite", "Oil change"),
                            ("neumaticos", "Tires"),
                            ("revision_tecnica", "Technical inspection"),
                            ("permiso_circulacion", "Vehicle permit"),
                            ("otro", "Other"),
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=200, blank=True, default="")),
                (
                    "service_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("service_time", models.TimeField(null=True, blank=True)),
                (
                    "kilometraje_declarado",
                    models.PositiveIntegerField(
                        null=True, blank=True, help_text="Odometer (miles)"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        max_digits=12, decimal_places=2, default=Decimal("0.00")
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "next_due_km",
                    models.PositiveIntegerField(
                        null=True, blank=True, help_text="Next due (miles)"
                    ),
                ),
                ("next_due_date", models.DateField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "service_type_obj",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.vehicleservicetype",
                    ),
                ),
            ],
            options={"ordering": ["-service_date", "-id"]},
        ),
        # ==========================================================
        # 8) VehicleNotificationConfig (nuevo)
        # ==========================================================
        migrations.CreateModel(
            name="VehicleNotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("include_assigned_driver", models.BooleanField(default=True)),
                ("extra_emails_to", models.TextField(blank=True, default="")),
                ("extra_emails_cc", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_cfg",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        # ==========================================================
        # 9) FlotaCronDiarioEjecutado
        # ==========================================================
        migrations.CreateModel(
            name="FlotaCronDiarioEjecutado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="flotacrondiarioejecutado",
            constraint=models.UniqueConstraint(
                fields=("nombre", "fecha"), name="uniq_fleet_cron_por_dia"
            ),
        ),
        # ==========================================================
        # 10) FlotaAlertaEnviada
        # ==========================================================
        migrations.CreateModel(
            name="FlotaAlertaEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pre_km", "Pre miles"),
                            ("pre_days", "Pre days"),
                            ("overdue_km", "Overdue miles"),
                            ("overdue_days", "Overdue days"),
                        ],
                    ),
                ),
                ("threshold", models.PositiveIntegerField(default=0)),
                ("sent_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_sent",
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_sent",
                        to="fleet.vehicleservicetype",
                    ),
                ),
                (
                    "base_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_base",
                        to="fleet.vehicleservice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vehicle", "service_type", "base_service", "mode"],
                        name="fleet_flota_vehicle_e3c356_idx",
                    ),
                    models.Index(
                        fields=["sent_on"], name="fleet_flota_sent_on_21c830_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="flotaalertaenviada",
            constraint=models.UniqueConstraint(
                fields=(
                    "vehicle",
                    "service_type",
                    "base_service",
                    "mode",
                    "threshold",
                    "sent_on",
                ),
                name="uniq_fleet_alert_combo",
            ),
        ),
    ]
