# Generated by Django 5.2.1 on 2026-04-09
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_ensure_vehicleservicetype_table"),
    ]

    operations = [
        # =========================
        # 1) FlotaCronDiarioEjecutado
        # =========================
        migrations.CreateModel(
            name="FlotaCronDiarioEjecutado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="flotacrondiarioejecutado",
            constraint=models.UniqueConstraint(
                fields=("nombre", "fecha"),
                name="uniq_fleet_cron_por_dia",
            ),
        ),
        # =========================
        # 2) FlotaAlertaEnviada
        # =========================
        migrations.CreateModel(
            name="FlotaAlertaEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("pre_km", "Pre miles"),
                            ("pre_days", "Pre days"),
                            ("overdue_km", "Overdue miles"),
                            ("overdue_days", "Overdue days"),
                        ],
                    ),
                ),
                ("threshold", models.PositiveIntegerField(default=0)),
                ("sent_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_base",
                        to="fleet.vehicleservice",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_sent",
                        to="fleet.vehicleservicetype",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_sent",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="flotaalertaenviada",
            index=models.Index(
                fields=["vehicle", "service_type", "base_service", "mode"],
                name="fleet_alert_idx1",
            ),
        ),
        migrations.AddIndex(
            model_name="flotaalertaenviada",
            index=models.Index(
                fields=["sent_on"],
                name="fleet_alert_sent_on",
            ),
        ),
        migrations.AddConstraint(
            model_name="flotaalertaenviada",
            constraint=models.UniqueConstraint(
                fields=(
                    "vehicle",
                    "service_type",
                    "base_service",
                    "mode",
                    "threshold",
                    "sent_on",
                ),
                name="uniq_fleet_alert_combo",
            ),
        ),
    ]
