# Generated by Django 5.2.1 on 2026-04-07 01:44

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicleodometerevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleodometerevent',
            options={'ordering': ['-event_at', '-id']},
        ),
        migrations.RenameField(
            model_name='vehicleodometerevent',
            old_name='date',
            new_name='event_at',
        ),
        migrations.AlterField(
            model_name='vehicleodometerevent',
            name='odometer_photo',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to='fleet/odometer_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
