# Generated by Django 5.2.1 on 2026-04-08 01:02
from django.db import migrations, models


def fill_vehicle_vin(apps, schema_editor):
    Vehicle = apps.get_model("fleet", "Vehicle")

    # Rellenar vin a los existentes (17 chars)
    for v in Vehicle.objects.all().only("id", "vin"):
        cur = (getattr(v, "vin", None) or "").strip()
        if cur:
            continue
        v.vin = f"TMP{v.id:014d}"  # ej: TMP00000000000001
        v.save(update_fields=["vin"])


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0004_alter_vehicleodometerevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                max_length=17,
                unique=True,
                db_index=True,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(fill_vehicle_vin, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                max_length=17,
                unique=True,
                db_index=True,
            ),
        ),
    ]
