# Generated by Django 5.2.1 on 2026-04-09 06:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_cartolamovimiento_service_date_and_more'),
        ('fleet', '0004_services_and_alerts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleodometerevent',
            options={'ordering': ['-event_at', '-id']},
        ),
        migrations.RenameIndex(
            model_name='flotaalertaenviada',
            new_name='fleet_flota_vehicle_e3c356_idx',
            old_name='fleet_alert_idx1',
        ),
        migrations.RenameIndex(
            model_name='flotaalertaenviada',
            new_name='fleet_flota_sent_on_21c830_idx',
            old_name='fleet_alert_sent_on',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='event_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='odometer_photo',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to='fleet/odometer_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='vehicleodometerevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proyecto'),
        ),
    ]
