# fleet/migrations/0006_ensure_vehicleservicetype_table.py
from django.db import migrations

CREATE_SQL = """
CREATE TABLE IF NOT EXISTS fleet_vehicleservicetype (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    interval_km INTEGER NULL,
    interval_days INTEGER NULL,

    alert_before_km INTEGER NULL,
    alert_before_days INTEGER NULL,

    alert_before_km_steps VARCHAR(120) NOT NULL DEFAULT '',
    alert_before_days_steps VARCHAR(120) NOT NULL DEFAULT '',

    notify_on_overdue BOOLEAN NOT NULL DEFAULT FALSE
);
"""

DROP_SQL = """
DROP TABLE IF EXISTS fleet_vehicleservicetype CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0005_vehicle_vin"),
    ]

    operations = [
        migrations.RunSQL(CREATE_SQL, reverse_sql=DROP_SQL),
    ]
