# Generated by Django 5.2.1 on 2026-04-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0006_ensure_vehicleservicetype_table"),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotaCronDiarioEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nombre', 'fecha'), name='uniq_fleet_cron_por_dia')],
            },
        ),
        migrations.CreateModel(
            name='FlotaAlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pre_km', 'Pre miles'), ('pre_days', 'Pre days'), ('overdue_km', 'Overdue miles'), ('overdue_days', 'Overdue days')], max_length=20)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_base', to='fleet.vehicleservice')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='fleet.vehicleservicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='fleet.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'service_type', 'base_service', 'mode'], name='fleet_flota_vehicle_e3c356_idx'), models.Index(fields=['sent_on'], name='fleet_flota_sent_on_21c830_idx')],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'service_type', 'base_service', 'mode', 'threshold', 'sent_on'), name='uniq_fleet_alert_combo')],
            },
        ),
    ]
