# Generated by Django 5.2.1 on 2026-04-09 00:00

from django.db import migrations, models

CREATE_SQL = """
CREATE TABLE IF NOT EXISTS fleet_vehicleservicetype (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    interval_km INTEGER NULL,
    interval_days INTEGER NULL,

    alert_before_km INTEGER NULL,
    alert_before_days INTEGER NULL,

    alert_before_km_steps VARCHAR(120) NOT NULL DEFAULT '',
    alert_before_days_steps VARCHAR(120) NOT NULL DEFAULT '',

    notify_on_overdue BOOLEAN NOT NULL DEFAULT FALSE
);
"""

DROP_SQL = """
DROP TABLE IF EXISTS fleet_vehicleservicetype CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0005_vehicle_vin"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_SQL, reverse_sql=DROP_SQL),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="VehicleServiceType",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=120)),
                        ("is_active", models.BooleanField(default=True)),
                        (
                            "interval_km",
                            models.PositiveIntegerField(
                                blank=True, null=True, help_text="Interval (miles)"
                            ),
                        ),
                        (
                            "interval_days",
                            models.PositiveIntegerField(
                                blank=True, null=True, help_text="Interval (days)"
                            ),
                        ),
                        (
                            "alert_before_km",
                            models.PositiveIntegerField(
                                blank=True, null=True, help_text="Alert before (miles)"
                            ),
                        ),
                        (
                            "alert_before_days",
                            models.PositiveIntegerField(
                                blank=True, null=True, help_text="Alert before (days)"
                            ),
                        ),
                        (
                            "alert_before_km_steps",
                            models.CharField(
                                max_length=120,
                                blank=True,
                                default="",
                                help_text="CSV miles steps: e.g. 1000,500,100",
                            ),
                        ),
                        (
                            "alert_before_days_steps",
                            models.CharField(
                                max_length=120,
                                blank=True,
                                default="",
                                help_text="CSV days steps: e.g. 30,10,5",
                            ),
                        ),
                        ("notify_on_overdue", models.BooleanField(default=False)),
                    ],
                    options={"ordering": ["name"]},
                ),
            ],
        ),
    ]
