# Generated by Django 5.2.1 on 2025-08-05 21:20

import django.core.validators
import storages.backends.s3
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartolaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rut_factura', models.CharField(blank=True, max_length=12, null=True)),
                ('tipo_doc', models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('otros', 'Otros')], max_length=20, null=True, verbose_name='Tipo de Documento')),
                ('numero_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Documento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_transferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='facturacion/cartolamovimiento/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante')),
                ('cargos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendiente_abono_usuario', 'Pending User Approval'), ('aprobado_abono_usuario', 'Credit Approved by User'), ('rechazado_abono_usuario', 'Credit Rejected by User'), ('pendiente_supervisor', 'Pending Supervisor Approval'), ('aprobado_supervisor', 'Approved by Supervisor'), ('rechazado_supervisor', 'Rejected by Supervisor'), ('aprobado_pm', 'Approved by PM'), ('rechazado_pm', 'Rejected by PM'), ('aprobado_finanzas', 'Approved by Finance'), ('rechazado_finanzas', 'Rejected by Finance')], default='pendiente_abono_usuario', max_length=50)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hes', models.CharField(blank=True, max_length=50, null=True, verbose_name='HES')),
                ('valor_en_clp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor en CLP')),
                ('conformidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conformidad')),
                ('num_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Facturación')),
                ('mes_produccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mes de Producción')),
                ('factorizado', models.BooleanField(default=False, verbose_name='¿Factorizado?')),
                ('fecha_factoring', models.DateField(blank=True, null=True, verbose_name='Fecha de Factoring')),
                ('cobrado', models.BooleanField(default=False, verbose_name='¿Cobrado?')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(blank=True, max_length=30, null=True, verbose_name='Orden de Compra')),
                ('pos', models.CharField(blank=True, max_length=10, null=True, verbose_name='POS')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(blank=True, max_length=10, null=True, verbose_name='UM')),
                ('material_servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material/Servicio')),
                ('descripcion_sitio', models.TextField(blank=True, null=True, verbose_name='Descripción / Sitio')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Unitario')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra Facturación',
                'verbose_name_plural': 'Órdenes de Compra Facturación',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mandante', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('costo', 'Costo'), ('inversion', 'Inversión'), ('gasto', 'Gasto'), ('abono', 'Abono')], max_length=50)),
            ],
        ),
    ]
