# Generated by Django 5.2.1 on 2025-07-20 15:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(blank=True, max_length=30, null=True, verbose_name='Orden de Compra')),
                ('pos', models.CharField(blank=True, max_length=10, null=True, verbose_name='POS')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(blank=True, max_length=10, null=True, verbose_name='UM')),
                ('material_servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material/Servicio')),
                ('descripcion_sitio', models.TextField(blank=True, null=True, verbose_name='Descripción / Sitio')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Unitario')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('du', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='operaciones.serviciocotizado')),
            ],
            options={
                'verbose_name': 'Orden de Compra Facturación',
                'verbose_name_plural': 'Órdenes de Compra Facturación',
            },
        ),
    ]
