# Generated by Django 5.2.1 on 2025-07-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hes', models.CharField(blank=True, max_length=50, null=True, verbose_name='HES')),
                ('valor_en_clp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor en CLP')),
                ('conformidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conformidad')),
                ('num_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Facturación')),
                ('mes_produccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mes de Producción')),
                ('factorizado', models.BooleanField(default=False, verbose_name='¿Factorizado?')),
                ('fecha_factoring', models.DateField(blank=True, null=True, verbose_name='Fecha de Factoring')),
                ('cobrado', models.BooleanField(default=False, verbose_name='¿Cobrado?')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='facturacion.ordencomprafacturacion', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
