# Generated by Django 5.2.1 on 2025-08-05 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='aprobado_por_finanzas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_aprobadas_finanzas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='aprobado_por_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_aprobadas_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='aprobado_por_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_aprobadas_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencomprafacturacion',
            name='du',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='operaciones.serviciocotizado'),
        ),
        migrations.AddField(
            model_name='facturaoc',
            name='orden_compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='facturacion.ordencomprafacturacion', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proyecto'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.tipogasto'),
        ),
    ]
