# Generated by Django 5.2.1 on 2025-08-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipogasto',
            name='categoria',
            field=models.CharField(choices=[('costo', 'Cost'), ('inversion', 'Investment'), ('gasto', 'Expense'), ('abono', 'Deposit')], max_length=50),
        ),
    ]
