# Generated by Django 5.2.1 on 2025-08-04 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='facturacion/cartolamovimiento/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante'),
        ),
    ]
