# Generated by Django 5.2.1 on 2025-07-27 18:04

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_facturaoc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('costo', 'Costo'), ('inversion', 'Inversión'), ('gasto', 'Gasto'), ('abono', 'Abono')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartolaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comprobante', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Comprobante')),
                ('cargos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendiente_abono_usuario', 'Pendiente aprobación abono usuario'), ('aprobado_abono_usuario', 'Aprobado abono por usuario'), ('rechazado_abono_usuario', 'Rechazado abono por usuario'), ('pendiente_supervisor', 'Pendiente aprobación supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_pm', 'Aprobado por PM'), ('rechazado_pm', 'Rechazado por PM'), ('aprobado_finanzas', 'Aprobado por finanzas'), ('rechazado_finanzas', 'Rechazado por finanzas')], default='pendiente_supervisor', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proyecto')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.tipogasto')),
            ],
        ),
    ]
