# Generated by Django 5.2.1 on 2025-08-04 22:24

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_cartolamovimiento_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='facturacion/cartolamovimiento/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='status',
            field=models.CharField(choices=[('pendiente_abono_usuario', 'Pending User Approval'), ('aprobado_abono_usuario', 'Credit Approved by User'), ('rechazado_abono_usuario', 'Credit Rejected by User'), ('pendiente_supervisor', 'Pending Supervisor Approval'), ('aprobado_supervisor', 'Approved by Supervisor'), ('rechazado_supervisor', 'Rejected by Supervisor'), ('aprobado_pm', 'Approved by PM'), ('rechazado_pm', 'Rejected by PM'), ('aprobado_finanzas', 'Approved by Finance'), ('rechazado_finanzas', 'Rejected by Finance')], default='pendiente_abono_usuario', max_length=50),
        ),
    ]
