# Generated by Django 5.2.1 on 2025-08-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_tipogasto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencomprafacturacion',
            name='du',
        ),
        migrations.DeleteModel(
            name='FacturaOC',
        ),
        migrations.DeleteModel(
            name='OrdenCompraFacturacion',
        ),
    ]
