# Generated by Django 5.2.1 on 2025-07-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_proyecto_tipogasto_cartolamovimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='numero_transferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
