# Generated by Django 5.2.1 on 2025-08-08 21:44

import django.core.validators
import storages.backends.s3
import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_ordencomprafacturacion_du_delete_facturaoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=utils.paths.upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante'),
        ),
    ]
