# Generated by Django 5.2.1 on 2025-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_cartolamovimiento_numero_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='mandante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
