# Generated by Django 5.2.1 on 2025-09-22 13:46

import django.core.validators
import storages.backends.s3
import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_cartolamovimiento_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='foto_tablero',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=utils.paths.upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Foto tablero (odómetro)'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, help_text='Kilometraje del vehículo (km)', null=True),
        ),
    ]
