# Generated by Django 5.2.1 on 2025-07-27 23:20

import cloudinary_storage.storage
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_proyecto_mandante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=facturacion.models.ruta_comprobante_cartola, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='status',
            field=models.CharField(choices=[('pendiente_abono_usuario', 'Pendiente aprobación abono usuario'), ('aprobado_abono_usuario', 'Aprobado abono por usuario'), ('rechazado_abono_usuario', 'Rechazado abono por usuario'), ('pendiente_supervisor', 'Pendiente aprobación supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_pm', 'Aprobado por PM'), ('rechazado_pm', 'Rechazado por PM'), ('aprobado_finanzas', 'Aprobado por finanzas'), ('rechazado_finanzas', 'Rechazado por finanzas')], default='pendiente_abono_usuario', max_length=50),
        ),
    ]
