# Generated by Django 5.2.1 on 2025-09-23 14:18

import django.core.validators
import storages.backends.s3
import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_cartolamovimiento_foto_tablero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=utils.paths.upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='foto_tablero',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=utils.paths.upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Odometer photo (dashboard)'),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, help_text='Vehicle odometer (km)', null=True),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='numero_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='tipo_doc',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('otros', 'Otros')], max_length=20, null=True, verbose_name='Document Type'),
        ),
    ]
