# Generated by Django 5.2.1 on 2025-07-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_cartolamovimiento_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
