# Generated by Django 5.2.1 on 2025-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_cartolamovimiento_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='oficina',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
