# Generated by Django 5.2.1 on 2025-07-28 03:43

import cloudinary_storage.storage
import django.core.validators
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_cartolamovimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=facturacion.models.ruta_comprobante_cartola, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprobante'),
        ),
    ]
