# Generated by Django 5.2.1 on 2025-07-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_cartolamovimiento_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='numero_doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='tipo_doc',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
