# Generated by Django 5.2.1 on 2025-11-11 17:52

from django.db import migrations
from django.utils import timezone


def backfill_timestamps(apps, schema_editor):
    Proyecto = apps.get_model("facturacion", "Proyecto")
    now = timezone.now()

    batch = []
    BATCH = 1000
    for p in Proyecto.objects.only("id", "created_at", "updated_at").iterator():
        changed = False
        if p.created_at is None:
            p.created_at = now
            changed = True
        if p.updated_at is None:
            p.updated_at = now
            changed = True
        if changed:
            batch.append(p)
            if len(batch) >= BATCH:
                Proyecto.objects.bulk_update(batch, ["created_at", "updated_at"])
                batch.clear()
    if batch:
        Proyecto.objects.bulk_update(batch, ["created_at", "updated_at"])

class Migration(migrations.Migration):
    dependencies = [
        ('facturacion', '0008_proyecto_activo_proyecto_ciudad_proyecto_codigo_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_timestamps, migrations.RunPython.noop),
    ]