# Generated by Django 5.2.1 on 2025-07-30 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_cartolamovimiento_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='aprobado_por_finanzas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_aprobadas_finanzas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='aprobado_por_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_aprobadas_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='aprobado_por_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_aprobadas_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
