# Generated by Django 5.2.1 on 2025-08-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_cartolamovimiento_aprobado_por_finanzas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='rut_factura',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cartolamovimiento',
            name='tipo_doc',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('otros', 'Otros')], max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
