# Generated by Django 5.2.1 on 2025-11-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_alter_proyecto_ciudad_alter_proyecto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='ciudad',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='mandante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='oficina',
            field=models.CharField(max_length=128),
        ),
    ]
