# Generated by Django 5.2.1 on 2025-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_proyecto_ciudad_alter_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('nombre', 'mandante', 'ciudad', 'estado', 'oficina'), name='uq_proyecto_nombre_mandante_ciudad_estado_oficina'),
        ),
    ]
