# Generated by Django 5.2.1 on 2026-04-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_fix_real_consumption_date_nullable'),
        ('fleet', '0002_vehiclenotificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='service_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartola_movimientos', to='fleet.vehicleservicetype'),
        ),
    ]
