# Generated by Django 5.2.1 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0017_cartolamovimiento_service_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipogasto",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
