# Generated by Django 5.2.1 on 2026-04-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_tipogasto_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'ordering': ['nombre']},
        ),
    ]
