# Generated by Django 5.2.1 on 2025-08-05 21:35

import datetime
import django.utils.timezone
import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=utils.paths.upload_to, verbose_name='Archivo del contrato')),
            ],
        ),
        migrations.CreateModel(
            name='CronogramaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enero_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('enero_fecha', models.DateField(blank=True, null=True)),
                ('febrero_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('febrero_fecha', models.DateField(blank=True, null=True)),
                ('marzo_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('marzo_fecha', models.DateField(blank=True, null=True)),
                ('abril_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('abril_fecha', models.DateField(blank=True, null=True)),
                ('mayo_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('mayo_fecha', models.DateField(blank=True, null=True)),
                ('junio_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('junio_fecha', models.DateField(blank=True, null=True)),
                ('julio_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('julio_fecha', models.DateField(blank=True, null=True)),
                ('agosto_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('agosto_fecha', models.DateField(blank=True, null=True)),
                ('septiembre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('septiembre_fecha', models.DateField(blank=True, null=True)),
                ('octubre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('octubre_fecha', models.DateField(blank=True, null=True)),
                ('noviembre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('noviembre_fecha', models.DateField(blank=True, null=True)),
                ('diciembre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('diciembre_fecha', models.DateField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiasVacacionesTomadosManualmente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_dias', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to=utils.paths.upload_to, verbose_name='Archivo del documento')),
                ('subido_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FichaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('hijos', models.IntegerField(blank=True, null=True)),
                ('nivel_estudios', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion_u_oficio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('parentesco_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_emergencia', models.CharField(blank=True, max_length=255, null=True)),
                ('afp', models.CharField(blank=True, max_length=100, null=True)),
                ('salud', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('banco_2', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta_2', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cuenta_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('jefe_directo', models.CharField(blank=True, max_length=100, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('jornada', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('sueldo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bono', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('colacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('movilizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('talla_polera', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_zapato', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pm', 'Pendiente revisión del PM'), ('rechazada_pm', 'Rechazada por el PM'), ('pendiente_usuario', 'Pendiente aprobación del trabajador'), ('rechazada_usuario', 'Rechazada por el trabajador'), ('aprobada', 'Aprobada con firmas')], default='pendiente_pm', max_length=30)),
                ('motivo_rechazo_pm', models.TextField(blank=True, null=True)),
                ('motivo_rechazo_usuario', models.TextField(blank=True, null=True)),
                ('firma_trabajador', models.ImageField(blank=True, null=True, upload_to=utils.paths.upload_to)),
                ('firma_pm', models.ImageField(blank=True, null=True, upload_to=utils.paths.upload_to)),
                ('firma_rrhh', models.ImageField(blank=True, null=True, upload_to=utils.paths.upload_to)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to, verbose_name='Comprobante firmado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.PositiveIntegerField()),
                ('monto_aprobado', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pm', 'Pendiente aprobación PM'), ('rechazada_pm', 'Rechazada por PM'), ('pendiente_rrhh', 'Pendiente aprobación RRHH'), ('rechazada_rrhh', 'Rechazada por RRHH'), ('aprobada', 'Aprobada')], default='pendiente_pm', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comprobante_transferencia', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to)),
                ('planilla_pdf', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to)),
                ('puede_editar_rrhh', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_solicitud', models.CharField(choices=[('total', 'Total'), ('parcial', 'Parcial')], default='total', max_length=10)),
                ('estatus', models.CharField(choices=[('pendiente_supervisor', 'Pendiente de Supervisor'), ('rechazada_supervisor', 'Rechazada por Supervisor'), ('pendiente_pm', 'Pendiente de PM'), ('rechazada_pm', 'Rechazada por PM'), ('pendiente_rrhh', 'Pendiente de RRHH'), ('rechazada_rrhh', 'Rechazada por RRHH'), ('rechazada_admin', 'Rechazada por Admin'), ('aprobada', 'Aprobada')], default='pendiente_supervisor', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(default=datetime.date.today)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to, verbose_name='Comprobante firmado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('vigencia_meses', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
