# Generated by Django 5.2.1 on 2025-06-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratotrabajo',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
