# Generated by Django 5.2.1 on 2025-08-04 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratotrabajo',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diasvacacionestomadosmanualmente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_manuales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudadelanto',
            name='aprobado_por_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_aprobados_como_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudadelanto',
            name='aprobado_por_rrhh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_aprobados_como_rrhh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudadelanto',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_adelanto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_rrhh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas_rrhh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentotrabajador',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipodocumento'),
        ),
    ]
