# Generated by Django 5.2.1 on 2025-06-13 03:20

import cloudinary_storage.storage
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_alter_contratotrabajo_fecha_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratotrabajo',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_contrato_trabajo, verbose_name='Archivo del contrato'),
        ),
    ]
