# Generated by Django 5.2.1 on 2025-08-08 20:12

import django.core.validators
import django.db.models.deletion
import rrhh.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file_unsigned', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=rrhh.models.rate_sheet_unsigned_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Unsigned PDF')),
                ('file_signed', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=rrhh.models.rate_sheet_signed_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Signed PDF')),
                ('status', models.CharField(choices=[('pending', 'Pending Signature'), ('signed', 'Signed')], default='pending', max_length=16, verbose_name='Status')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signed At')),
                ('technician_signature', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=rrhh.models.tech_signature_path, verbose_name='Technician Signature')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Technician')),
            ],
        ),
    ]
