# Generated by Django 5.2.1 on 2025-06-14 04:39

import cloudinary_storage.storage
import django.db.models.deletion
import rrhh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_alter_contratotrabajo_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_ficha_ingreso, verbose_name='Ficha de Ingreso (PDF)')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
