# Generated by Django 5.2.1 on 2025-08-09 04:08

import rrhh.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_usersignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignature',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=rrhh.models.upload_to_signature),
        ),
    ]
