# Generated by Django 5.2.1 on 2025-06-15 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_fichaingreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.FloatField()),
                ('estatus', models.CharField(choices=[('pendiente_supervisor', 'Pendiente de Supervisor'), ('rechazada_supervisor', 'Rechazada por Supervisor'), ('pendiente_pm', 'Pendiente de PM'), ('rechazada_pm', 'Rechazada por PM'), ('pendiente_rrhh', 'Pendiente de RRHH'), ('rechazada_rrhh', 'Rechazada por RRHH'), ('aprobada', 'Aprobada')], default='pendiente_supervisor', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
