# Generated by Django 5.2.1 on 2025-06-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_feriado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feriado',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
