# Generated by Django 5.2.1 on 2025-06-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_solicitudvacaciones_aprobado_por_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estatus',
            field=models.CharField(choices=[('pendiente_supervisor', 'Pendiente de Supervisor'), ('rechazada_supervisor', 'Rechazada por Supervisor'), ('pendiente_pm', 'Pendiente de PM'), ('rechazada_pm', 'Rechazada por PM'), ('pendiente_rrhh', 'Pendiente de RRHH'), ('rechazada_rrhh', 'Rechazada por RRHH'), ('rechazada_admin', 'Rechazada por Admin'), ('aprobada', 'Aprobada')], default='pendiente_supervisor', max_length=30),
        ),
    ]
