# Generated by Django 5.2.1 on 2025-06-19 13:33

import cloudinary_storage.storage
import datetime
import django.db.models.deletion
import django.utils.timezone
import rrhh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_tipodocumento_documentotrabajador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentotrabajador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentotrabajador',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 19, 13, 33, 34, 741278, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentotrabajador',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_documento_trabajador, verbose_name='Archivo del documento'),
        ),
        migrations.AlterField(
            model_name='documentotrabajador',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentotrabajador',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentotrabajador',
            name='subido_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
