# Generated by Django 5.2.1 on 2025-06-19 21:37

import cloudinary_storage.storage
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_alter_documentotrabajador_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_solicitud_vacaciones, verbose_name='Comprobante firmado'),
        ),
    ]
