# Generated by Django 5.2.1 on 2025-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_solicitudvacaciones_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='tipo_solicitud',
            field=models.CharField(choices=[('total', 'Total'), ('parcial', 'Parcial')], default='total', max_length=10),
        ),
    ]
