# Generated by Django 5.2.1 on 2025-06-20 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0014_solicitudvacaciones_tipo_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaingreso',
            name='archivo',
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='afp',
            field=models.CharField(default='Sin AFP', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='banco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='bono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='cargo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='colacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='comuna',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='estado_civil',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='faena',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='hijos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='jornada',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='movilizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='nacionalidad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='nivel_estudios',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='nombre_contacto_emergencia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='parentesco_emergencia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='profesion_u_oficio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='rut',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='salud',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='sueldo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='telefono_emergencia',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='tipo_cuenta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
