# Generated by Django 5.2.1 on 2025-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0015_remove_fichaingreso_archivo_fichaingreso_afp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaingreso',
            name='banco_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='numero_cuenta_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='tipo_cuenta_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
