# Generated by Django 5.2.1 on 2025-06-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_fichaingreso_banco_2_fichaingreso_numero_cuenta_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaingreso',
            name='tecnico',
        ),
    ]
