# Generated by Django 5.2.1 on 2025-06-20 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0017_remove_fichaingreso_tecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaingreso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='fichas_ingreso/'),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
