# Generated by Django 5.2.1 on 2025-06-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0018_fichaingreso_archivo_fichaingreso_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaingreso',
            name='afp',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='banco_2',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='bono',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='colacion',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='hijos',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='movilizacion',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='nivel_estudios',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='numero_cuenta_2',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='profesion_u_oficio',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='salud',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='tipo_cuenta_2',
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='firma_trabajador',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='faena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='jornada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='nombre_contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='sueldo_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaingreso',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
