# Generated by Django 5.2.1 on 2025-06-20 23:17

import cloudinary_storage.storage
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0021_fichaingreso_afp_fichaingreso_banco_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaingreso',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_ficha_ingreso, verbose_name='Comprobante firmado'),
        ),
    ]
