# Generated by Django 5.2.1 on 2025-06-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0022_alter_fichaingreso_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
