# Generated by Django 5.2.1 on 2025-06-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0023_fichaingreso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente_pm', 'Pendiente revisión del PM'), ('rechazada_pm', 'Rechazada por el PM'), ('pendiente_usuario', 'Pendiente aprobación del trabajador'), ('rechazada_usuario', 'Rechazada por el trabajador'), ('aprobada', 'Aprobada con firmas')], default='pendiente_pm', max_length=30),
        ),
    ]
