# Generated by Django 5.2.1 on 2025-06-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0024_alter_fichaingreso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaingreso',
            name='motivo_rechazo_pm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='motivo_rechazo_usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
