# Generated by Django 5.2.1 on 2025-06-23 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0025_fichaingreso_motivo_rechazo_pm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enero_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('enero_fecha', models.DateField(blank=True, null=True)),
                ('febrero_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('febrero_fecha', models.DateField(blank=True, null=True)),
                ('marzo_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('marzo_fecha', models.DateField(blank=True, null=True)),
                ('abril_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('abril_fecha', models.DateField(blank=True, null=True)),
                ('mayo_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('mayo_fecha', models.DateField(blank=True, null=True)),
                ('junio_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('junio_fecha', models.DateField(blank=True, null=True)),
                ('julio_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('julio_fecha', models.DateField(blank=True, null=True)),
                ('agosto_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('agosto_fecha', models.DateField(blank=True, null=True)),
                ('septiembre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('septiembre_fecha', models.DateField(blank=True, null=True)),
                ('octubre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('octubre_fecha', models.DateField(blank=True, null=True)),
                ('noviembre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('noviembre_fecha', models.DateField(blank=True, null=True)),
                ('diciembre_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('diciembre_fecha', models.DateField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
