# Generated by Django 5.2.1 on 2025-06-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0027_remove_cronogramapago_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaingreso',
            old_name='faena',
            new_name='jefe_directo',
        ),
        migrations.AddField(
            model_name='fichaingreso',
            name='proyecto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
