# Generated by Django 5.2.1 on 2025-06-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0028_rename_faena_fichaingreso_jefe_directo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaingreso',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='fichaingreso',
            name='sueldo_liquido',
        ),
    ]
