# Generated by Django 5.2.1 on 2025-06-26 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0029_remove_fichaingreso_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.PositiveIntegerField()),
                ('monto_aprobado', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pm', 'Pendiente aprobación PM'), ('rechazada_pm', 'Rechazada por PM'), ('pendiente_rrhh', 'Pendiente aprobación RRHH'), ('rechazada_rrhh', 'Rechazada por RRHH'), ('aprobada', 'Aprobada')], default='pendiente_pm', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprobante_transferencia', models.FileField(blank=True, null=True, upload_to='media/Solicitud de adelanto de sueldo/comprobantes/')),
                ('planilla_pdf', models.FileField(blank=True, null=True, upload_to='media/Solicitud de adelanto de sueldo/planillas/')),
                ('aprobado_por_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_aprobados_como_pm', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por_rrhh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_aprobados_como_rrhh', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_adelanto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
