# Generated by Django 5.2.1 on 2025-06-27 01:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0030_solicitudadelanto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadelanto',
            name='comprobante_transferencia',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='Solicitud de adelanto de sueldo/comprobantes/'),
        ),
        migrations.AlterField(
            model_name='solicitudadelanto',
            name='planilla_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='Solicitud de adelanto de sueldo/planillas/'),
        ),
    ]
