# Generated by Django 5.2.1 on 2025-06-27 01:53

import cloudinary_storage.storage
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0031_alter_solicitudadelanto_comprobante_transferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadelanto',
            name='comprobante_transferencia',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_archivos_adelanto),
        ),
        migrations.AlterField(
            model_name='solicitudadelanto',
            name='planilla_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=rrhh.models.ruta_archivos_adelanto),
        ),
    ]
