# Generated by Django 5.2.1 on 2025-06-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0032_alter_solicitudadelanto_comprobante_transferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadelanto',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
