# Generated by Django 5.2.1 on 2025-06-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0033_alter_solicitudadelanto_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadelanto',
            name='puede_editar_rrhh',
            field=models.BooleanField(default=False),
        ),
    ]
