# Generated by Django 5.2.1 on 2026-09-09 23:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('default_unit', models.CharField(choices=[('box', 'Box'), ('ft', 'Foot'), ('site', 'Site'), ('ea', 'Each'), ('hour', 'Hour'), ('day', 'Day'), ('other', 'Other')], default='other', max_length=20)),
                ('default_resource_type', models.CharField(choices=[('crew', 'Crew'), ('technician', 'Technician'), ('other', 'Other')], default='crew', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planning Activity Type',
                'verbose_name_plural': 'Planning Activity Types',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PlanningCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('daily_work_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planning Calendar',
                'verbose_name_plural': 'Planning Calendars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('market', models.CharField(blank=True, db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_plans_created', to=settings.AUTH_USER_MODEL)),
                ('default_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_plans', to='planificacion.planningcalendar')),
            ],
            options={
                'verbose_name': 'Master Plan',
                'verbose_name_plural': 'Master Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('frozen', 'Frozen'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('assumptions_snapshot', models.JSONField(blank=True, default=dict, help_text='Historical snapshot of global assumptions used when this version was calculated/frozen.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_plan_versions_created', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_plan_versions_frozen', to=settings.AUTH_USER_MODEL)),
                ('master_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planificacion.masterplan')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_plan_versions', to='planificacion.planningcalendar')),
            ],
            options={
                'verbose_name': 'Master Plan Version',
                'verbose_name_plural': 'Master Plan Versions',
                'ordering': ['master_plan', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanningCalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working_day', models.BooleanField(help_text='Enable when this date must count as a working day, even if its weekday is normally non-working.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='planificacion.planningcalendar')),
            ],
            options={
                'verbose_name': 'Planning Calendar Exception',
                'verbose_name_plural': 'Planning Calendar Exceptions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PlanningDFN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('pc', models.CharField(blank=True, max_length=80)),
                ('market', models.CharField(blank=True, db_index=True, max_length=120)),
                ('contractor', models.CharField(blank=True, max_length=150)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], db_index=True, default='draft', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Optional reference to the source document, email, NTP number, or other client assignment reference.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_dfns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning DFN',
                'verbose_name_plural': 'Planning DFNs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlanningBaselineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('client_start_date', models.DateField(blank=True, null=True)),
                ('client_end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unit', models.CharField(choices=[('box', 'Box'), ('ft', 'Foot'), ('site', 'Site'), ('ea', 'Each'), ('hour', 'Hour'), ('day', 'Day'), ('other', 'Other')], default='other', max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('client_total', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_activities', to='planificacion.planningactivitytype')),
                ('dfn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_activities', to='planificacion.planningdfn')),
            ],
            options={
                'verbose_name': 'Client Baseline Activity',
                'verbose_name_plural': 'Client Baseline Activities',
                'ordering': ['dfn__code', 'sequence', 'activity_type__code'],
            },
        ),
        migrations.CreateModel(
            name='MasterPlanDFN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(db_index=True, default=1)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfn_entries', to='planificacion.masterplanversion')),
                ('dfn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_plan_entries', to='planificacion.planningdfn')),
            ],
            options={
                'verbose_name': 'Master Plan DFN',
                'verbose_name_plural': 'Master Plan DFNs',
                'ordering': ['version', 'priority', 'dfn__code'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('resource_type', models.CharField(choices=[('crew', 'Crew'), ('technician', 'Technician'), ('other', 'Other')], max_length=20)),
                ('production_rate', models.DecimalField(decimal_places=4, help_text='Production per resource per working day.', max_digits=14)),
                ('unit', models.CharField(choices=[('box', 'Box'), ('ft', 'Foot'), ('site', 'Site'), ('ea', 'Each'), ('hour', 'Hour'), ('day', 'Day'), ('other', 'Other')], max_length=20)),
                ('default_resource_count', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productivity_profiles', to='planificacion.planningactivitytype')),
            ],
            options={
                'verbose_name': 'Productivity Profile',
                'verbose_name_plural': 'Productivity Profiles',
                'ordering': ['activity_type__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MasterPlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(choices=[('box', 'Box'), ('ft', 'Foot'), ('site', 'Site'), ('ea', 'Each'), ('hour', 'Hour'), ('day', 'Day'), ('other', 'Other')], default='other', max_length=20)),
                ('resource_type', models.CharField(choices=[('crew', 'Crew'), ('technician', 'Technician'), ('other', 'Other')], max_length=20)),
                ('resource_count', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('production_rate', models.DecimalField(decimal_places=4, help_text='Production per resource per working day.', max_digits=14)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('calculated_workdays', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated working-day duration stored as part of this Master Plan version.', max_digits=10, null=True)),
                ('assumptions_snapshot', models.JSONField(blank=True, default=dict, help_text='Optional extra assumptions specific to this activity.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_plan_dfn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planificacion.masterplandfn')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_plan_activities', to='planificacion.planningactivitytype')),
                ('baseline_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_plan_activities', to='planificacion.planningbaselineactivity')),
                ('productivity_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_plan_activities', to='planificacion.productivityprofile')),
            ],
            options={
                'verbose_name': 'Master Plan Activity',
                'verbose_name_plural': 'Master Plan Activities',
                'ordering': ['master_plan_dfn', 'sequence', 'activity_type__code'],
            },
        ),
        migrations.CreateModel(
            name='MasterPlanActivityDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lag_workdays', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='planificacion.masterplanactivity')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='planificacion.masterplanactivity')),
            ],
            options={
                'verbose_name': 'Master Plan Activity Dependency',
                'verbose_name_plural': 'Master Plan Activity Dependencies',
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='uniq_master_plan_activity_dependency')],
            },
        ),
        migrations.AddConstraint(
            model_name='masterplanversion',
            constraint=models.UniqueConstraint(fields=('master_plan', 'version_number'), name='uniq_master_plan_version_number'),
        ),
        migrations.AddConstraint(
            model_name='planningcalendarexception',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='uniq_planning_calendar_exception_date'),
        ),
        migrations.AddConstraint(
            model_name='masterplandfn',
            constraint=models.UniqueConstraint(fields=('version', 'dfn'), name='uniq_dfn_per_master_plan_version'),
        ),
    ]
