# Generated by Django 5.2.1 on 2026-09-10 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(db_index=True, default=1)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Plan Assignment',
                'verbose_name_plural': 'Master Plan Assignments',
                'ordering': ['version', 'priority', 'assignment__name'],
            },
        ),
        migrations.CreateModel(
            name='PlanningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('client_reference', models.CharField(blank=True, db_index=True, help_text='Client assignment reference, NTP number, Work Order, or other external identifier.', max_length=150)),
                ('assignment_type', models.CharField(blank=True, help_text='Optional descriptive type such as NTP, Work Order, Project Package, etc.', max_length=80)),
                ('issue_date', models.DateField(blank=True, db_index=True, null=True)),
                ('pc', models.CharField(blank=True, help_text='Optional PC or equivalent client identifier.', max_length=80)),
                ('contractor', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Optional source document, email reference, uploaded file or other origin reference.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planning Assignment',
                'verbose_name_plural': 'Planning Assignments',
                'ordering': ['-issue_date', 'client__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanningClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional internal or client-facing short code.', max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planning Client',
                'verbose_name_plural': 'Planning Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanningLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, max_length=120)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('market', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planning Location',
                'verbose_name_plural': 'Planning Locations',
                'ordering': ['country', 'state', 'city', 'market'],
            },
        ),
        migrations.AlterModelOptions(
            name='masterplanactivity',
            options={'ordering': ['master_plan_assignment', 'sequence', 'activity_type__code'], 'verbose_name': 'Master Plan Activity', 'verbose_name_plural': 'Master Plan Activities'},
        ),
        migrations.AlterModelOptions(
            name='masterplandfn',
            options={'ordering': ['master_plan_assignment', 'sequence', 'dfn__code'], 'verbose_name': 'Master Plan DFN', 'verbose_name_plural': 'Master Plan DFNs'},
        ),
        migrations.AlterModelOptions(
            name='planningbaselineactivity',
            options={'ordering': ['assignment', 'sequence', 'activity_type__code'], 'verbose_name': 'Client Baseline Activity', 'verbose_name_plural': 'Client Baseline Activities'},
        ),
        migrations.RemoveConstraint(
            model_name='masterplandfn',
            name='uniq_dfn_per_master_plan_version',
        ),
        migrations.RenameField(
            model_name='masterplandfn',
            old_name='priority',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='masterplan',
            name='market',
        ),
        migrations.RemoveField(
            model_name='masterplandfn',
            name='version',
        ),
        migrations.RemoveField(
            model_name='planningdfn',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='planningdfn',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='planningdfn',
            name='market',
        ),
        migrations.RemoveField(
            model_name='planningdfn',
            name='pc',
        ),
        migrations.RemoveField(
            model_name='planningdfn',
            name='source_reference',
        ),
        migrations.AlterField(
            model_name='masterplanactivity',
            name='master_plan_dfn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planificacion.masterplandfn'),
        ),
        migrations.AlterField(
            model_name='masterplandfn',
            name='dfn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_plan_dfn_entries', to='planificacion.planningdfn'),
        ),
        migrations.AlterField(
            model_name='masterplanversion',
            name='assumptions_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Historical snapshot of global assumptions used when this version was calculated or frozen.'),
        ),
        migrations.AlterField(
            model_name='planningbaselineactivity',
            name='dfn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseline_activities', to='planificacion.planningdfn'),
        ),
        migrations.AlterField(
            model_name='planningdfn',
            name='code',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='masterplanassignment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_entries', to='planificacion.masterplanversion'),
        ),
        migrations.AddField(
            model_name='masterplanactivity',
            name='master_plan_assignment',
            field=models.ForeignKey(blank=True, help_text='Master Plan Assignment that owns this activity. Nullable during migration from the original DFN-only model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planificacion.masterplanassignment'),
        ),
        migrations.AddField(
            model_name='masterplandfn',
            name='master_plan_assignment',
            field=models.ForeignKey(blank=True, help_text='Master Plan Assignment that owns this DFN entry. Nullable during migration from the original DFN-only model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dfn_entries', to='planificacion.masterplanassignment'),
        ),
        migrations.AddIndex(
            model_name='masterplanactivity',
            index=models.Index(fields=['master_plan_assignment', 'sequence'], name='master_act_asg_sequence_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterplandfn',
            constraint=models.UniqueConstraint(fields=('master_plan_assignment', 'dfn'), name='uniq_dfn_per_master_plan_assignment'),
        ),
        migrations.AddField(
            model_name='planningassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterplanassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_plan_entries', to='planificacion.planningassignment'),
        ),
        migrations.AddField(
            model_name='planningbaselineactivity',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment that owns this baseline activity. Nullable during the initial migration from the DFN-only structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseline_activities', to='planificacion.planningassignment'),
        ),
        migrations.AddField(
            model_name='planningdfn',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment that owns this DFN. Nullable during the initial migration from the legacy PlanningDFN structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dfns', to='planificacion.planningassignment'),
        ),
        migrations.AddIndex(
            model_name='planningbaselineactivity',
            index=models.Index(fields=['assignment', 'client_end_date'], name='planning_base_asg_end_idx'),
        ),
        migrations.AddIndex(
            model_name='planningdfn',
            index=models.Index(fields=['assignment', 'status'], name='planning_dfn_asg_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='planningdfn',
            constraint=models.UniqueConstraint(fields=('assignment', 'code'), name='uniq_dfn_code_per_assignment'),
        ),
        migrations.AddField(
            model_name='planningassignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='planificacion.planningclient'),
        ),
        migrations.AddIndex(
            model_name='planninglocation',
            index=models.Index(fields=['city', 'market'], name='planning_loc_city_market_idx'),
        ),
        migrations.AddField(
            model_name='planningassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='planificacion.planninglocation'),
        ),
        migrations.AddIndex(
            model_name='masterplanassignment',
            index=models.Index(fields=['version', 'priority'], name='mp_asg_ver_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterplanassignment',
            constraint=models.UniqueConstraint(fields=('version', 'assignment'), name='uniq_assignment_per_master_plan_version'),
        ),
        migrations.AddIndex(
            model_name='planningassignment',
            index=models.Index(fields=['client', 'status'], name='planning_asg_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='planningassignment',
            index=models.Index(fields=['location', 'status'], name='planning_asg_loc_status_idx'),
        ),
    ]
