# Generated by Django 5.2.1 on 2026-09-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_masterplanassignment_planningassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterplanassignment',
            name='calendar',
            field=models.ForeignKey(blank=True, help_text='Assignment-specific working calendar used by the High-Level Plan. When empty, the Master Plan version/default calendar is used.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_plan_assignments', to='planificacion.planningcalendar'),
        ),
    ]
