# Generated by Django 5.2.1 on 2026-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_masterplanassignment_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningactivitytype',
            options={'ordering': ['display_order', 'code', 'name'], 'verbose_name': 'Planning Activity Type', 'verbose_name_plural': 'Planning Activity Types'},
        ),
        migrations.AlterField(
            model_name='planningactivitytype',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='planningactivitytype',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='uniq_planning_activity_code_name'),
        ),
    ]
