# Generated by Django 5.2.1 on 2026-09-14 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0050_bulkbillingpreview'),
        ('planificacion', '0004_alter_planningactivitytype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealPlanProjectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_position', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('planning_mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], db_index=True, default='auto', max_length=16)),
                ('original_planned_date', models.DateField(blank=True, null=True)),
                ('carried_over', models.BooleanField(db_index=True, default=False)),
                ('carry_over_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_plan_state', to='operaciones.sesionbilling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_plan_project_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Real Plan Project State',
                'verbose_name_plural': 'Real Plan Project States',
                'ordering': ('board_position', 'billing_id'),
                'indexes': [models.Index(fields=['planning_mode', 'board_position'], name='realplan_mode_pos_idx'), models.Index(fields=['carried_over', 'updated_at'], name='realplan_carry_idx')],
            },
        ),
    ]
