# Generated by Django 5.2.1 on 2026-09-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_realplanuserpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealPlanDailyRollover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField(db_index=True, unique=True)),
                ('target_date', models.DateField(db_index=True)),
                ('moved_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Real Plan Daily Rollover',
                'verbose_name_plural': 'Real Plan Daily Rollovers',
                'ordering': ('-source_date',),
            },
        ),
    ]
