# Generated by Django 5.2.1 on 2025-11-12 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_proyecto_uq_proyecto_nombre_mandante_ciudad_estado_oficina'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_history', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='facturacion.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoasignacion_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='usuarios.ProyectoAsignacion', to='facturacion.proyecto'),
        ),
    ]
