# Generated by Django 5.2.1 on 2025-06-12 04:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_firma_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='firmas/'),
        ),
    ]
