# Generated by Django 5.2.1 on 2025-07-01 19:29

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_firmarepresentantelegal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmarepresentantelegal',
            name='archivo',
            field=models.FileField(upload_to=usuarios.models.ruta_firma_representante),
        ),
    ]
