# Generated by Django 5.2.1 on 2025-07-01 19:39

import cloudinary_storage.storage
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_firmarepresentantelegal_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmarepresentantelegal',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=usuarios.models.ruta_firma_representante, verbose_name='Firma del Representante Legal'),
        ),
        migrations.AlterField(
            model_name='firmarepresentantelegal',
            name='fecha_subida',
            field=models.DateTimeField(),
        ),
    ]
