# Generated by Django 5.2.1 on 2025-06-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_firma_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('supervisor', 'Supervisor'), ('pm', 'Project Manager'), ('rrhh', 'Recursos Humanos'), ('admin', 'Administrador General')], default='tecnico', max_length=20),
        ),
    ]
