# Generated by Django 5.2.1 on 2025-06-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('supervisor', 'Supervisor'), ('pm', 'Project Manager'), ('rrhh', 'Recursos Humanos'), ('prevencion', 'Prevención de Riesgo'), ('logistica', 'Logística'), ('flota', 'Flota'), ('subcontrato', 'Subcontrato'), ('facturacion', 'Facturación'), ('admin', 'Administrador General')], default='usuario', max_length=20),
        ),
    ]
