# Generated by Django 5.2.1 on 2025-07-05 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='creada_en',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='para_roles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
