# Generated by Django 5.2.1 on 2025-07-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='para_roles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
