# Generated by Django 5.2.1 on 2025-06-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rol_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
    ]
