# Generated by Django 5.2.1 on 2025-07-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_notificacion_para_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='leida',
            new_name='leido',
        ),
    ]
