# Generated by Django 5.2.1 on 2025-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dias_vacaciones_consumidos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Días de vacaciones que ya ha consumido fuera del sistema', max_digits=6),
        ),
    ]
