# Generated by Django 5.2.1 on 2025-07-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_customuser_encargado_facturacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='encargado_facturacion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='encargado_flota',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='encargado_subcontrato',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='logistica_encargado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pm',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prevencionista',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rrhh_encargado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='supervisor',
        ),
    ]
