# Generated by Django 5.2.1 on 2025-07-09 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_customuser_encargado_facturacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_bodeguero_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodeguero', to=settings.AUTH_USER_MODEL),
        ),
    ]
