# Generated by Django 5.2.1 on 2026-06-25 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0019_alter_tipogasto_options'),
        ('operaciones', '0043_alter_requirementlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=20)),
                ('expiration_mode', models.CharField(choices=[('none', 'No expiration'), ('days', 'Expires in days'), ('date', 'Specific expiration date')], default='none', max_length=20)),
                ('expiration_days', models.PositiveIntegerField(blank=True, help_text='Cantidad de días de vigencia si expiration_mode=days.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Si está vacío, el link no expira.', null=True)),
                ('requires_access_key', models.BooleanField(default=False, help_text='Si está activo, el cliente debe ingresar una clave para abrir el link.')),
                ('access_key_hash', models.CharField(blank=True, help_text='Clave hasheada. Nunca guardar clave en texto plano.', max_length=255)),
                ('access_key_hint', models.CharField(blank=True, help_text='Referencia opcional, no debe revelar la clave.', max_length=120)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Mensaje interno/opcional para el paquete.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages_published', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_packages_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Package',
                'verbose_name_plural': 'Delivery Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPackageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=120)),
                ('file_type', models.CharField(choices=[('client_report', 'Client Report'), ('photo_report', 'Photo Report'), ('photos_zip', 'Photos ZIP'), ('light_levels', 'Light Levels'), ('operational_report', 'Operational Report'), ('manual_file', 'Manual File'), ('other', 'Other')], default='other', max_length=40)),
                ('display_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='client_deliverables/%Y/%m/')),
                ('source_url', models.TextField(blank=True, help_text='URL interna o externa desde donde se puede generar/descargar el archivo.')),
                ('source_key', models.TextField(blank=True, help_text='Storage key opcional si el archivo vive en Wasabi/S3.')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_files', to='operaciones.sesionbilling')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_files_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='client_deliverables.deliverypackage')),
            ],
            options={
                'verbose_name': 'Delivery Package File',
                'verbose_name_plural': 'Delivery Package Files',
                'ordering': ['project_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('unlock_success', 'Unlock success'), ('unlock_failed', 'Unlock failed'), ('download_file', 'Download file'), ('download_all', 'Download all'), ('revoked_access', 'Revoked access'), ('expired_access', 'Expired access')], max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_access_logs', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='client_deliverables.deliverypackage')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='client_deliverables.deliverypackagefile')),
            ],
            options={
                'verbose_name': 'Delivery Access Log',
                'verbose_name_plural': 'Delivery Access Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, help_text='Project ID visible en Billing/operaciones.', max_length=120)),
                ('client_name', models.CharField(blank=True, help_text='Nombre del cliente/empresa para referencia.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_project_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_assignments', to='facturacion.proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Project Assignment',
                'verbose_name_plural': 'Client Project Assignments',
                'indexes': [models.Index(fields=['user', 'project_id'], name='client_deli_user_id_23f76e_idx'), models.Index(fields=['project_id', 'is_active'], name='client_deli_project_b70188_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project_id'), name='unique_client_project_assignment')],
            },
        ),
        migrations.AddIndex(
            model_name='deliverypackage',
            index=models.Index(fields=['status', 'expires_at'], name='client_deli_status_222160_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypackage',
            index=models.Index(fields=['token'], name='client_deli_token_e67b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypackagefile',
            index=models.Index(fields=['package', 'project_id'], name='client_deli_package_27ef7b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypackagefile',
            index=models.Index(fields=['project_id', 'file_type'], name='client_deli_project_668252_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaccesslog',
            index=models.Index(fields=['package', 'action'], name='client_deli_package_13a0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaccesslog',
            index=models.Index(fields=['created_at'], name='client_deli_created_8e6692_idx'),
        ),
    ]
