# Generated by Django 5.2.1 on 2026-06-29 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_deliverables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZipJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='client_deliverables/zips/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('files_added', models.PositiveIntegerField(default=0)),
                ('files_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_jobs', to='client_deliverables.deliverypackage')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_zip_jobs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery ZIP Job',
                'verbose_name_plural': 'Delivery ZIP Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['package', 'status'], name='client_deli_package_0008ed_idx'), models.Index(fields=['created_at'], name='client_deli_created_25572a_idx')],
            },
        ),
    ]
