# Generated by Django 5.2.1 on 2026-06-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_deliverables', '0002_deliveryzipjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypackage',
            name='access_key_plain',
            field=models.CharField(blank=True, help_text='Clave visible para copiar y enviar al cliente por otro canal.', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverypackage',
            name='access_key_hash',
            field=models.CharField(blank=True, help_text='Clave hasheada. Se usa para validar la clave de acceso.', max_length=255),
        ),
    ]
