# Generated by Django 5.2.1 on 2026-07-22 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_deliverables', '0003_deliverypackage_access_key_plain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzipjob',
            name='content_signature',
            field=models.CharField(blank=True, db_index=True, help_text='Firma de los deliverables incluidos. Permite reutilizar un ZIP solo cuando el contenido del package no ha cambiado.', max_length=64),
        ),
        migrations.AddField(
            model_name='deliveryzipjob',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha en que el ZIP temporal debe dejar de reutilizarse.', null=True),
        ),
        migrations.AddField(
            model_name='deliveryzipjob',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Última fecha en que el ZIP generado fue descargado.', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzipjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliveryzipjob',
            index=models.Index(fields=['status', 'expires_at'], name='client_deli_status_c96a85_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzipjob',
            index=models.Index(fields=['package', 'content_signature', 'status'], name='client_deli_package_180e96_idx'),
        ),
    ]
