# Generated by Django 5.2.1 on 2025-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mnemonic'),
        ),
    ]
