# Generated by Django 5.2.1 on 2025-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_customer_mnemonic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
