# Generated by Django 5.2.1 on 2025-10-23 17:27

import django.db.models.deletion
import invoicing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_alter_customer_mnemonic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=invoicing.models.brand_logo_upload_to)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_logos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=7)),
                ('accent_color', models.CharField(default='#22c55e', max_length=7)),
                ('invoice_prefix', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding_settings', to=settings.AUTH_USER_MODEL)),
                ('default_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoicing.brandlogo')),
            ],
        ),
    ]
