# Generated by Django 5.2.1 on 2025-10-23 17:44

import django.core.validators
import invoicing.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_brandlogo_brandingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='file',
            field=models.ImageField(max_length=1024, storage=storages.backends.s3.S3Storage(), upload_to=invoicing.models.upload_to_brand_logo, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='brandlogo',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
