# Generated by Django 5.2.1 on 2025-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_brandingprofile_brandingsettings_default_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingprofile',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='brandingprofile',
            name='company_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brandingprofile',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='brandingprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='brandingprofile',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
