# Generated by Django 5.2.1 on 2025-10-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_brandingprofile_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingprofile',
            name='template_key',
            field=models.CharField(blank=True, default='classic', max_length=30),
        ),
    ]
