# Generated by Django 5.2.1 on 2025-10-23 21:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_brandingprofile_template_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.CharField(blank=True, default='', max_length=120)),
                ('office', models.CharField(blank=True, default='', max_length=120)),
                ('client', models.CharField(blank=True, default='', max_length=160)),
                ('work_type', models.CharField(blank=True, default='', max_length=120)),
                ('job_code', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('uom', models.CharField(blank=True, default='', max_length=30, verbose_name='Unit of Measure')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_code'],
            },
        ),
    ]
