# Generated by Django 5.2.1 on 2025-10-23 22:17

import django.db.models.deletion
import django.utils.timezone
import invoicing.models
import storages.backends.s3
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_itemcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pdf', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=invoicing.models.upload_to_invoice_pdf)),
                ('template_key', models.CharField(blank=True, default='classic', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branding_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoicing.brandingprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'indexes': [models.Index(fields=['owner', 'number'], name='invoicing_i_owner_i_5177db_idx'), models.Index(fields=['owner', 'issue_date'], name='invoicing_i_owner_i_147b37_idx'), models.Index(fields=['owner', 'status'], name='invoicing_i_owner_i_eedb7c_idx')],
                'unique_together': {('owner', 'number')},
            },
        ),
    ]
