# Generated by Django 5.2.1 on 2025-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingprofile',
            name='company_state',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brandingprofile',
            name='company_zip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
