# Generated by Django 5.2.1 on 2025-10-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_brandingprofile_company_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Issued (Pending)'), ('overdue', 'Overdue — Collect'), ('paid', 'Paid'), ('void', 'Void')], default=[('pending', 'Issued (Pending)'), ('overdue', 'Overdue — Collect'), ('paid', 'Paid'), ('void', 'Void')], max_length=10),
        ),
    ]
