# Generated by Django 5.2.1 on 2025-10-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_invoice_due_date_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcode',
            name='lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
