# Generated by Django 5.2.1 on 2025-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_itemcode_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcode',
            name='lines',
        ),
        migrations.AddField(
            model_name='invoice',
            name='lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
