# Generated by Django 5.2.1 on 2025-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_remove_itemcode_lines_invoice_lines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcode',
            options={'ordering': ['city', 'job_code']},
        ),
        migrations.AlterField(
            model_name='itemcode',
            name='job_code',
            field=models.CharField(max_length=60),
        ),
        migrations.AddConstraint(
            model_name='itemcode',
            constraint=models.UniqueConstraint(fields=('job_code', 'city'), name='uniq_itemcode_jobcode_city'),
        ),
    ]
