# Generated by Django 5.2.1 on 2025-10-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0015_alter_itemcode_options_alter_itemcode_job_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente'),
        ),
    ]
