# Generated by Django 5.2.1 on 2025-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0016_customer_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cliente',
        ),
        migrations.AddField(
            model_name='customer',
            name='client',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Client'),
        ),
    ]
