# Generated by Django 5.2.1 on 2025-12-10 14:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_invoice_notes_invoice_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat discount amount subtracted from subtotal+tax', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (e.g. 19.00 for 19%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Issued (Pending)'), ('overdue', 'Overdue — Collect'), ('paid', 'Paid'), ('void', 'Void')], default='pending', max_length=10),
        ),
    ]
