# Generated by Django 5.2.1 on 2026-05-05 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0019_invoice_discount_amount_invoice_subtotal_and_more'),
        ('operaciones', '0037_billingpayweeksnapshot_adjustment_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operaciones.sesionbilling'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_session'], name='invoicing_i_billing_b984ae_idx'),
        ),
    ]
