# Generated by Django 5.2.1 on 2025-08-05 21:35

import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du', models.CharField(blank=True, max_length=20, unique=True)),
                ('id_claro', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_produccion', models.CharField(max_length=20)),
                ('id_new', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle_tarea', models.TextField()),
                ('monto_cotizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_mmoo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado_pendiente', 'Aprobada, pendiente por asignar'), ('asignado', 'Técnicos asignados'), ('en_progreso', 'En progreso'), ('finalizado_trabajador', 'Finalizado por técnico'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('informe_subido', 'Informe cargado'), ('finalizado', 'Finalizado')], default='cotizado', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion_supervisor', models.DateTimeField(blank=True, null=True, verbose_name='Fecha aprobación del supervisor')),
                ('informe', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to, verbose_name='Informe del servicio')),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SitioMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sites', models.CharField(max_length=100, unique=True)),
                ('id_claro', models.CharField(blank=True, max_length=100, null=True)),
                ('id_sites_new', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_construccion', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.CharField(blank=True, max_length=100, null=True)),
                ('candado_bt', models.CharField(blank=True, max_length=100, null=True)),
                ('condiciones_acceso', models.TextField(blank=True, null=True)),
                ('claves', models.TextField(blank=True, null=True)),
                ('llaves', models.TextField(blank=True, null=True)),
                ('cantidad_llaves', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('zonas_conflictivas', models.TextField(blank=True, null=True)),
                ('alarmas', models.TextField(blank=True, null=True)),
                ('guardias', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
