# Generated by Django 5.2.1 on 2025-07-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sites', models.CharField(max_length=100, unique=True)),
                ('id_claro', models.CharField(blank=True, max_length=100, null=True)),
                ('id_sites_new', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_construccion', models.CharField(blank=True, max_length=100, null=True)),
                ('altura', models.CharField(blank=True, max_length=100, null=True)),
                ('candado_bt', models.CharField(blank=True, max_length=100, null=True)),
                ('condiciones_acceso', models.TextField(blank=True, null=True)),
                ('claves', models.TextField(blank=True, null=True)),
                ('llaves', models.TextField(blank=True, null=True)),
                ('cantidad_llaves', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('zonas_conflictivas', models.TextField(blank=True, null=True)),
                ('alarmas', models.TextField(blank=True, null=True)),
                ('guardias', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du', models.CharField(max_length=20, unique=True)),
                ('id_claro', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('mes_produccion', models.CharField(max_length=20)),
                ('id_new', models.CharField(max_length=100)),
                ('detalle_tarea', models.TextField()),
                ('monto_cotizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_mmoo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado_pendiente', 'Aprobada, pendiente por asignar'), ('asignado', 'Técnicos asignados'), ('en_progreso', 'En progreso'), ('finalizado_trabajador', 'Finalizado por técnico'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('informe_subido', 'Informe cargado'), ('finalizado', 'Finalizado')], default='cotizado', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
                ('pm_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas_pm', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por PM')),
                ('supervisor_aprobo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_aprobados_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por supervisor')),
                ('supervisor_asigna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados_como_supervisor', to=settings.AUTH_USER_MODEL)),
                ('supervisor_rechazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_rechazados_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por supervisor')),
                ('tecnico_aceptado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_aceptados_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Aceptado por técnico')),
                ('tecnico_finalizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_finalizados_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por técnico')),
                ('trabajadores_asignados', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'usuario'}, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos asignados')),
            ],
        ),
    ]
