# Generated by Django 5.2.1 on 2025-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitioMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sites', models.CharField(max_length=50, verbose_name='ID Sites')),
                ('id_claro', models.CharField(max_length=50, verbose_name='ID Claro')),
                ('id_sites_new', models.CharField(max_length=50, verbose_name='ID Sites NEW')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('tipo_construccion', models.CharField(max_length=100, verbose_name='Tipo de construcción')),
                ('altura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Altura')),
                ('candado_bt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Candado BT')),
                ('condiciones_acceso', models.TextField(blank=True, null=True, verbose_name='Condiciones de acceso')),
                ('claves', models.CharField(blank=True, max_length=255, null=True, verbose_name='Claves')),
                ('llaves', models.CharField(blank=True, max_length=255, null=True, verbose_name='Llaves')),
                ('cantidad_llaves', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cantidad de Llaves')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('zonas_conflictivas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sitios zonas conflictivas')),
                ('alarmas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alarmas')),
                ('guardias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guardias')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Nivel')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
