# Generated by Django 5.2.1 on 2025-07-20 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizado',
            name='usuario_informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cargó el informe'),
        ),
    ]
