# Generated by Django 5.2.1 on 2025-08-05 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizado',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='pm_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas_pm', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por PM'),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='supervisor_aprobo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_aprobados_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por supervisor'),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='supervisor_asigna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados_como_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='supervisor_rechazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_rechazados_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por supervisor'),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='tecnico_aceptado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_aceptados_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Aceptado por técnico'),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='tecnico_finalizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_finalizados_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por técnico'),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='trabajadores_asignados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'usuario'}, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos asignados'),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='usuario_informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cargó el informe'),
        ),
    ]
