# Generated by Django 5.2.1 on 2025-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitiomovil',
            name='alarmas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='altura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='candado_bt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='cantidad_llaves',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='claves',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='condiciones_acceso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='guardias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='id_claro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='id_sites',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='id_sites_new',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='llaves',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='observaciones_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='tipo_construccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='zonas_conflictivas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
