# Generated by Django 5.2.1 on 2025-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_serviciocotizado_usuario_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizado',
            name='fecha_aprobacion_supervisor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha aprobación del supervisor'),
        ),
    ]
