# Generated by Django 5.2.1 on 2025-07-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_serviciocotizado_du'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocotizado',
            name='id_claro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviciocotizado',
            name='id_new',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviciocotizado',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
