# Generated by Django 5.2.1 on 2025-07-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_sitiomovil_alarmas_alter_sitiomovil_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitiomovil',
            name='altura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitiomovil',
            name='cantidad_llaves',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
