# Generated by Django 5.2.1 on 2025-08-07 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_ordencomprafacturacion_du_delete_facturaoc_and_more'),
        ('operaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioActividadTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('proyecto', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio_tecnico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Precio por Actividad',
                'verbose_name_plural': 'Precios por Actividad',
                'unique_together': {('tecnico', 'ciudad', 'proyecto', 'codigo')},
            },
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='pm_aprueba',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='supervisor_aprobo',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='supervisor_asigna',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='supervisor_rechazo',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='tecnico_aceptado',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='tecnico_finalizo',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='trabajadores_asignados',
        ),
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='usuario_informe',
        ),
        migrations.DeleteModel(
            name='SitioMovil',
        ),
        migrations.DeleteModel(
            name='ServicioCotizado',
        ),
    ]
