# Generated by Django 5.2.1 on 2025-08-08 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_precioactividadtecnico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='precioactividadtecnico',
            old_name='codigo',
            new_name='codigo_trabajo',
        ),
        migrations.AlterUniqueTogether(
            name='precioactividadtecnico',
            unique_together={('tecnico', 'ciudad', 'proyecto', 'codigo_trabajo')},
        ),
        migrations.AddField(
            model_name='precioactividadtecnico',
            name='cliente',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='precioactividadtecnico',
            name='oficina',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='precioactividadtecnico',
            name='tipo_trabajo',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
