# Generated by Django 5.2.1 on 2025-08-09 23:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_rename_codigo_precioactividadtecnico_codigo_trabajo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_trabajo', models.CharField(max_length=60)),
                ('tipo_trabajo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=40)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('precio_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_tecnico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SesionBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto_id', models.CharField(max_length=64)),
                ('cliente', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=120)),
                ('proyecto', models.CharField(max_length=120)),
                ('oficina', models.CharField(max_length=120)),
                ('subtotal_tecnico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('real_company_billing', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBillingTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tarifa_efectiva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desglose_tecnico', to='operaciones.itembilling')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itembilling',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones.sesionbilling'),
        ),
        migrations.CreateModel(
            name='SesionBillingTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos_sesion', to='operaciones.sesionbilling')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sesion', 'tecnico')},
            },
        ),
    ]
