# Generated by Django 5.2.1 on 2025-08-11 21:28

import django.db.models.deletion
import django.utils.timezone
import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_itembilling_sesionbilling_itembillingtecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='aceptado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('en_revision_supervisor', 'En revisión supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('aprobado_pm', 'Aprobado por PM'), ('rechazado_pm', 'Rechazado por PM')], default='asignado', max_length=32),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='pm_comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='pm_revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='reintento_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='reporte_fotografico',
            field=models.FileField(blank=True, null=True, upload_to=operaciones.models.upload_to_reporte_fotografico),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='supervisor_comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='supervisor_revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RequisitoFotoBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tecnico_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='operaciones.sesionbillingtecnico')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFotoBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=operaciones.models.upload_to_evidencia)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('tomada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('tecnico_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='operaciones.sesionbillingtecnico')),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='operaciones.requisitofotobilling')),
            ],
            options={
                'ordering': ('requisito__orden', 'tomada_en', 'id'),
            },
        ),
    ]
