# Generated by Django 5.2.1 on 2025-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_sesionbillingtecnico_aceptado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='client_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='gps_accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
