# Generated by Django 5.2.1 on 2025-08-12 21:30

import django.core.validators
import operaciones.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_evidenciafotobilling_client_taken_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembilling',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='itembillingtecnico',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='sesionbilling',
            options={'ordering': ('-creado_en',)},
        ),
        migrations.AlterModelOptions(
            name='sesionbillingtecnico',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='sesionbillingtecnico',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='imagen',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_evidencia, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='sesionbillingtecnico',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('en_revision_supervisor', 'En revisión supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('aprobado_pm', 'Aprobado por PM'), ('rechazado_pm', 'Rechazado por PM')], db_index=True, default='en_proceso', max_length=32),
        ),
        migrations.AlterField(
            model_name='sesionbillingtecnico',
            name='reporte_fotografico',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_reporte_fotografico, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'pdf'])]),
        ),
        migrations.AddIndex(
            model_name='evidenciafotobilling',
            index=models.Index(fields=['tecnico_sesion'], name='operaciones_tecnico_d0d99e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciafotobilling',
            index=models.Index(fields=['requisito'], name='operaciones_requisi_02d4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='itembilling',
            index=models.Index(fields=['sesion', 'codigo_trabajo'], name='operaciones_sesion__601a90_idx'),
        ),
        migrations.AddIndex(
            model_name='itembillingtecnico',
            index=models.Index(fields=['item', 'tecnico'], name='operaciones_item_id_343879_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitofotobilling',
            index=models.Index(fields=['tecnico_sesion', 'orden'], name='operaciones_tecnico_faa7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['proyecto_id'], name='operaciones_proyect_0b5c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['cliente', 'ciudad', 'proyecto', 'oficina'], name='operaciones_cliente_59317e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesionbillingtecnico',
            constraint=models.UniqueConstraint(fields=('sesion', 'tecnico'), name='uniq_sesion_tecnico'),
        ),
    ]
