# Generated by Django 5.2.1 on 2025-08-13 17:41

import django.core.validators
import operaciones.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_alter_itembilling_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado (pendiente revisión)'), ('en_revision_supervisor', 'En revisión supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('rechazado_pm', 'Rechazado por PM'), ('aprobado_pm', 'Aprobado por PM')], db_index=True, default='en_proceso', max_length=32),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='reporte_fotografico',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_reporte_fotografico_proyecto, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'pdf'])]),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['estado'], name='operaciones_estado_7d5927_idx'),
        ),
    ]
