# Generated by Django 5.2.1 on 2025-08-13 20:25

import django.core.validators
import operaciones.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_sesionbilling_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionbilling',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Assigned'), ('en_proceso', 'In progress'), ('en_revision_supervisor', 'Submitted — supervisor review'), ('rechazado_supervisor', 'Rejected by supervisor'), ('aprobado_supervisor', 'Approved by supervisor'), ('rechazado_pm', 'Rejected by PM'), ('aprobado_pm', 'Approved by PM')], db_index=True, default='asignado', max_length=32),
        ),
        migrations.AlterField(
            model_name='sesionbilling',
            name='reporte_fotografico',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_project_report, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='sesionbillingtecnico',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('en_revision_supervisor', 'En revisión supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('aprobado_pm', 'Aprobado por PM'), ('rechazado_pm', 'Rechazado por PM')], db_index=True, default='asignado', max_length=32),
        ),
    ]
