# Generated by Django 5.2.1 on 2025-08-14 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_alter_sesionbilling_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='precioactividadtecnico',
            unique_together={('tecnico', 'ciudad', 'proyecto', 'oficina', 'cliente', 'codigo_trabajo')},
        ),
        migrations.AddIndex(
            model_name='precioactividadtecnico',
            index=models.Index(fields=['tecnico', 'ciudad', 'proyecto', 'oficina', 'cliente', 'codigo_trabajo'], name='operaciones_tecnico_f0601b_idx'),
        ),
    ]
