# Generated by Django 5.2.1 on 2025-08-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_alter_precioactividadtecnico_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='direccion_proyecto',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Project address / Google Maps link'),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='semana_pago_proyectada',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Projected pay week (ISO)'),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='semana_pago_real',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Real pay week (ISO)'),
        ),
    ]
