# Generated by Django 5.2.1 on 2025-08-18 23:52

import django.core.validators
import operaciones.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_sesionbilling_direccion_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='imagen',
            field=models.ImageField(max_length=1024, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_evidencia, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='sesionbilling',
            name='reporte_fotografico',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_project_report, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='sesionbillingtecnico',
            name='reporte_fotografico',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_reporte_fotografico, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'pdf'])]),
        ),
    ]
