# Generated by Django 5.2.1 on 2025-08-20 19:58

import django.core.validators
import django.db.models.deletion
import operaciones.models
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_alter_evidenciafotobilling_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending_user', 'Pending worker approval'), ('approved_user', 'Approved by worker'), ('rejected_user', 'Rejected by worker'), ('pending_payment', 'Pending payment'), ('paid', 'Paid')], db_index=True, default='pending_user', max_length=20)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('paid_week', models.CharField(blank=True, default='', max_length=10)),
                ('receipt', models.FileField(blank=True, max_length=1024, null=True, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_payment_receipt, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week', 'technician_id'],
                'indexes': [models.Index(fields=['week', 'status'], name='operaciones_week_f6b764_idx'), models.Index(fields=['technician', 'week'], name='operaciones_technic_aa463b_idx')],
                'unique_together': {('technician', 'week')},
            },
        ),
    ]
