# Generated by Django 5.2.1 on 2025-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_weeklypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='direccion_manual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Custom address'),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='titulo_manual',
            field=models.CharField(blank=True, max_length=200, verbose_name='Custom title'),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='proyecto_especial',
            field=models.BooleanField(default=False, help_text="If enabled, 'extra' photos can include user-entered Title and Address; the report will use those fields."),
        ),
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='client_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taken at (client)'),
        ),
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='gps_accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='GPS accuracy (m)'),
        ),
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='evidenciafotobilling',
            name='nota',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note'),
        ),
    ]
