# Generated by Django 5.2.1 on 2025-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_evidenciafotobilling_direccion_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='finance_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='finance_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='finance_status',
            field=models.CharField(choices=[('none', '—'), ('sent', 'Enviado a Finanzas'), ('pending', 'Pendiente por cobrar'), ('in_review', 'En revisión'), ('rejected', 'Rechazado'), ('paid', 'Cobrado')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='finance_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
