# Generated by Django 5.2.1 on 2025-08-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0016_sesionbilling_finance_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioactividadtecnico',
            name='codigo_trabajo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='precioactividadtecnico',
            name='unidad_medida',
            field=models.CharField(max_length=60),
        ),
    ]
