# Generated by Django 5.2.1 on 2025-09-12 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_alter_precioactividadtecnico_codigo_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='is_direct_discount',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='origin_session',
            field=models.ForeignKey(blank=True, help_text='If set, this discount corrects the referenced session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='operaciones.sesionbilling'),
        ),
    ]
