# Generated by Django 5.2.1 on 2025-09-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0018_sesionbilling_is_direct_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='discount_week',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Discount week (ISO)'),
        ),
        migrations.AlterField(
            model_name='sesionbilling',
            name='finance_status',
            field=models.CharField(choices=[('none', '—'), ('review_discount', 'Review discount'), ('discount_applied', 'Discount applied'), ('sent', 'Enviado a Finanzas'), ('pending', 'Pendiente por cobrar'), ('in_review', 'En revisión'), ('rejected', 'Rechazado'), ('paid', 'Cobrado')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['is_direct_discount'], name='operaciones_is_dire_45a538_idx'),
        ),
    ]
