# Generated by Django 5.2.1 on 2025-09-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0019_sesionbilling_discount_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFotograficoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pending'), ('procesando', 'Processing'), ('ok', 'OK'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('procesadas', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('resultado_key', models.CharField(blank=True, max_length=512)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_reporte', to='operaciones.sesionbilling')),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['sesion', 'estado'], name='operaciones_sesion__be4586_idx')],
            },
        ),
    ]
