# Generated by Django 5.2.1 on 2025-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0020_reportefotograficojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefotograficojob',
            name='cancel_requested',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
