# Generated by Django 5.2.1 on 2025-10-02 14:41

import django.core.validators
import django.db.models.deletion
import operaciones.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0021_reportefotograficojob_cancel_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.PositiveIntegerField(db_index=True)),
                ('file', models.FileField(max_length=1024, storage=storages.backends.s3.S3Storage(), upload_to=operaciones.models.upload_to_plan, validators=[django.core.validators.FileExtensionValidator(['pdf', 'dwg', 'xlsx', 'xls'])])),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='operaciones.sesionbilling')),
            ],
            options={
                'ordering': ('plan_number', 'id'),
                'unique_together': {('sesion', 'plan_number')},
            },
        ),
    ]
