# Generated by Django 5.2.1 on 2025-10-03 18:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0022_projectplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(db_index=True, max_length=10)),
                ('client', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('project', models.CharField(blank=True, default='', max_length=120)),
                ('office', models.CharField(blank=True, default='', max_length=120)),
                ('project_id', models.CharField(blank=True, default='', max_length=64)),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('advance', 'Advance'), ('fixed_salary', 'Fixed salary')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week', '-id'),
                'indexes': [models.Index(fields=['technician', 'week'], name='operaciones_technic_dbc736_idx'), models.Index(fields=['adjustment_type'], name='operaciones_adjustm_a54bb2_idx')],
            },
        ),
    ]
