# Generated by Django 5.2.1 on 2025-10-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0024_sesionbilling_split_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sesionbilling',
            new_name='operaciones_is_spli_fe19cd_idx',
            old_name='operacione_is_spli_idx',
        ),
    ]
