# Generated by Django 5.2.1 on 2025-11-12 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_proyecto_uq_proyecto_nombre_mandante_ciudad_estado_oficina'),
        ('operaciones', '0025_rename_operacione_is_spli_idx_operaciones_is_spli_fe19cd_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='precioactividadtecnico',
            new_name='operaciones_tecnico_6fabcd_idx',
            old_name='operaciones_tecnico_f0601b_idx',
        ),
        migrations.AlterField(
            model_name='precioactividadtecnico',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_tecnico', to='facturacion.proyecto'),
        ),
    ]
