# Generated by Django 5.2.1 on 2025-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0026_rename_operaciones_tecnico_f0601b_idx_operaciones_tecnico_6fabcd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='finance_daily_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Daily Number'),
        ),
    ]
