# Generated by Django 5.2.1 on 2025-12-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0027_sesionbilling_finance_daily_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='finance_finish_date',
            field=models.DateField(blank=True, help_text='End date.', null=True, verbose_name='Finance finish date'),
        ),
    ]
