# Generated by Django 5.2.1 on 2026-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0028_sesionbilling_finance_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='tecnico_comentario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
