# Generated by Django 5.2.1 on 2026-03-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0029_sesionbillingtecnico_tecnico_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbillingtecnico',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
