# Generated by Django 5.2.1 on 2026-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0030_sesionbillingtecnico_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='tech_payment_mode',
            field=models.CharField(choices=[('split', 'Split (percentage)'), ('full', 'Full quantity per technician')], db_index=True, default='split', help_text='How technician amounts are computed. split = uses %; full = each tech uses full qty.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['tech_payment_mode'], name='operaciones_tech_pa_5786cb_idx'),
        ),
    ]
