# Generated by Django 5.2.1 on 2026-04-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0031_sesionbilling_tech_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='is_cable_installation',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, Requirements will use the Cable Installation workflow.'),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['is_cable_installation'], name='operaciones_is_cabl_d0ef8e_idx'),
        ),
    ]
