# Generated by Django 5.2.1 on 2026-04-27 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0032_sesionbilling_is_cable_installation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='power_dbm',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Extracted Power Meter reading in dBm (e.g., -21.05).', max_digits=7, null=True, verbose_name='Power (dBm)'),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='power_extract_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='power_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='power_extracted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_extractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisitofotobilling',
            name='needs_power_reading',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, this requirement expects a Power Meter reading (dBm).'),
        ),
        migrations.AddField(
            model_name='requisitofotobilling',
            name='power_port_no',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Optional port number (1..8) when title is POWER PORT X.', null=True),
        ),
        migrations.AddIndex(
            model_name='evidenciafotobilling',
            index=models.Index(fields=['power_dbm'], name='operaciones_power_d_15ea4a_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitofotobilling',
            index=models.Index(fields=['tecnico_sesion', 'needs_power_reading'], name='operaciones_tecnico_26925e_idx'),
        ),
    ]
