# Generated by Django 5.2.1 on 2026-05-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0033_evidenciafotobilling_power_dbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioactividadtecnico',
            name='payment_weeks',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of weeks to defer payment for this technician price.'),
        ),
    ]
