# Generated by Django 5.2.1 on 2026-05-05 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0034_precioactividadtecnico_payment_weeks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPayWeekSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_trabajo', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_trabajo', models.CharField(blank=True, default='', max_length=120)),
                ('payment_weeks', models.PositiveSmallIntegerField(default=0)),
                ('semana_base', models.CharField(blank=True, default='', help_text='Projected pay week captured at snapshot time.', max_length=10)),
                ('semana_resultado', models.CharField(blank=True, default='', help_text='Final real pay week for this technician/work type line.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_week_snapshots', to='operaciones.itembilling')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_week_snapshots', to='operaciones.sesionbilling')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_pay_week_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sesion_id', 'tecnico_id', 'id'),
                'indexes': [models.Index(fields=['sesion', 'tecnico'], name='operaciones_sesion__8acf6d_idx'), models.Index(fields=['sesion', 'semana_resultado'], name='operaciones_sesion__b1690e_idx'), models.Index(fields=['tecnico', 'semana_resultado'], name='operaciones_tecnico_b71b25_idx')],
            },
        ),
    ]
