# Generated by Django 5.2.1 on 2026-05-05 08:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0035_billingpayweeksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='tarifa_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='tarifa_efectiva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billingpayweeksnapshot',
            name='semana_base',
            field=models.CharField(blank=True, default='', help_text='Projected/base week captured at snapshot time.', max_length=10),
        ),
    ]
