# Generated by Django 5.2.1 on 2026-05-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0036_billingpayweeksnapshot_porcentaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='adjustment_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_children', to='operaciones.billingpayweeksnapshot'),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='is_adjustment',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued in weekly payment'), ('paid', 'Paid'), ('reopened', 'Reopened'), ('adjustment_pending', 'Adjustment pending'), ('adjustment_paid', 'Adjustment paid')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='billingpayweeksnapshot',
            name='weekly_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_lines', to='operaciones.weeklypayment'),
        ),
        migrations.AddIndex(
            model_name='billingpayweeksnapshot',
            index=models.Index(fields=['tecnico', 'payment_status'], name='operaciones_tecnico_6a5bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='billingpayweeksnapshot',
            index=models.Index(fields=['weekly_payment', 'payment_status'], name='operaciones_weekly__801fbf_idx'),
        ),
    ]
