# Generated by Django 5.2.1 on 2026-05-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0037_billingpayweeksnapshot_adjustment_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayment',
            name='paid_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Historical frozen amount when this weekly payment was marked as paid.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='weeklypayment',
            name='paid_breakdown_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Historical frozen breakdown of what was paid in this weekly payment.'),
        ),
        migrations.AddField(
            model_name='weeklypayment',
            name='paid_snapshot_at',
            field=models.DateTimeField(blank=True, help_text='When the historical paid snapshot was captured.', null=True),
        ),
    ]
