# Generated by Django 5.2.1 on 2026-06-11 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0038_weeklypayment_paid_amount_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafotobilling',
            name='light_source_dbm',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Extracted Light Source reading in dBm (e.g., -7.90).', max_digits=7, null=True, verbose_name='Light Source (dBm)'),
        ),
        migrations.AddField(
            model_name='requisitofotobilling',
            name='needs_light_source_reading',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, this requirement expects a Light Source reading (dBm).'),
        ),
        migrations.AddIndex(
            model_name='evidenciafotobilling',
            index=models.Index(fields=['light_source_dbm'], name='operaciones_light_s_30ddb2_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitofotobilling',
            index=models.Index(fields=['tecnico_sesion', 'needs_light_source_reading'], name='operaciones_tecnico_2b67e1_idx'),
        ),
    ]
