# Generated by Django 5.2.1 on 2026-06-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0039_evidenciafotobilling_light_source_dbm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoFotoBillingPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('needs_power_reading', models.BooleanField(db_index=True, default=False, help_text='If enabled, this requirement expects a Power Meter reading (dBm).')),
                ('needs_light_source_reading', models.BooleanField(db_index=True, default=False, help_text='If enabled, this requirement expects a Light Source reading (dBm).')),
                ('power_port_no', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Optional port number (1..8) when title is POWER PORT X.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_plantilla', to='operaciones.sesionbilling')),
            ],
            options={
                'ordering': ('orden', 'id'),
                'indexes': [models.Index(fields=['sesion', 'orden'], name='operaciones_sesion__ed37e9_idx'), models.Index(fields=['sesion', 'slug'], name='operaciones_sesion__4685d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'slug'), name='uniq_requisito_plantilla_sesion_slug')],
            },
        ),
    ]
