# Generated by Django 5.2.1 on 2026-06-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0040_requisitofotobillingplantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmententry',
            name='adjustment_type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('advance', 'Advance'), ('fixed_salary', 'Fixed salary'), ('allowance', 'Allowance')], max_length=20),
        ),
    ]
