# Generated by Django 5.2.1 on 2026-06-22 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_alter_tipogasto_options'),
        ('operaciones', '0041_alter_adjustmententry_adjustment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirement_lists', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_lists', to='facturacion.proyecto')),
            ],
            options={
                'ordering': ('project__nombre', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RequirementListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('needs_power_reading', models.BooleanField(db_index=True, default=False, help_text='If enabled, this requirement expects a Power Meter reading.')),
                ('needs_light_source_reading', models.BooleanField(db_index=True, default=False, help_text='If enabled, this requirement expects a Light Source reading.')),
                ('power_port_no', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Optional port number when title is POWER PORT X.', null=True)),
                ('requirement_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones.requirementlist')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='requirementlist',
            index=models.Index(fields=['project', 'is_active'], name='operaciones_project_168977_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementlist',
            index=models.Index(fields=['name'], name='operaciones_name_48e5aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementlist',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_requirement_list_project_name'),
        ),
        migrations.AddIndex(
            model_name='requirementlistitem',
            index=models.Index(fields=['requirement_list', 'order'], name='operaciones_require_b6cd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementlistitem',
            index=models.Index(fields=['requirement_list', 'slug'], name='operaciones_require_ed640e_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementlistitem',
            constraint=models.UniqueConstraint(fields=('requirement_list', 'slug'), name='uniq_requirement_list_item_slug'),
        ),
    ]
