# Generated by Django 5.2.1 on 2026-06-22 19:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_alter_tipogasto_options'),
        ('operaciones', '0042_requirementlist_requirementlistitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirementlist',
            options={'ordering': ('project__nombre', 'list_type', 'name')},
        ),
        migrations.RemoveConstraint(
            model_name='requirementlist',
            name='uniq_requirement_list_project_name',
        ),
        migrations.AddField(
            model_name='requirementlist',
            name='list_type',
            field=models.CharField(choices=[('fiber', 'Fiber / Photo requirements'), ('cable', 'Cable requirements')], db_index=True, default='fiber', help_text='Determines whether this list is used for fiber/photo requirements or cable requirements.', max_length=20),
        ),
        migrations.AddField(
            model_name='requirementlistitem',
            name='handhole',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Cable requirement handhole.', max_length=150),
        ),
        migrations.AddField(
            model_name='requirementlistitem',
            name='planned_reserve_ft',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Planned slack/reserve in feet for cable requirements.', max_digits=10),
        ),
        migrations.AddField(
            model_name='requirementlistitem',
            name='warning',
            field=models.CharField(blank=True, default='', help_text='Optional warning for technician.', max_length=255),
        ),
        migrations.AlterField(
            model_name='requirementlistitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='requirementlist',
            index=models.Index(fields=['project', 'list_type', 'is_active'], name='operaciones_project_6c455d_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementlist',
            index=models.Index(fields=['list_type'], name='operaciones_list_ty_f08500_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementlistitem',
            index=models.Index(fields=['requirement_list', 'handhole'], name='operaciones_require_157ee1_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementlist',
            constraint=models.UniqueConstraint(fields=('project', 'list_type', 'name'), name='uniq_requirement_list_project_type_name'),
        ),
    ]
