# Generated by Django 5.2.1 on 2026-07-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0043_alter_requirementlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionbilling',
            name='finance_status',
            field=models.CharField(choices=[('none', '—'), ('review_discount', 'Review discount'), ('discount_applied', 'Discount applied'), ('pending_send', 'Pending to send to client'), ('sent', 'Sent to client'), ('pending', 'Pending payment'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('paid', 'Collected')], db_index=True, default='none', max_length=32),
        ),
    ]
