# Generated by Django 5.2.1 on 2026-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0045_alter_sesionbilling_finance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='allow_gallery_upload',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, technicians may upload existing images from the gallery for requirements and extra photos. LIGHT SOURCE remains allowed even when this option is disabled.'),
        ),
    ]
