# Generated by Django 5.2.1 on 2026-09-08 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0046_sesionbilling_allow_gallery_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAssignmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_released', models.BooleanField(db_index=True, default=False, help_text='Whether this assignment is currently visible/actionable for the technician.')),
                ('released_manually', models.BooleanField(db_index=True, default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_state', to='operaciones.sesionbillingtecnico')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_queue_releases', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('technician_id', 'queue_position', 'id'),
                'indexes': [models.Index(fields=['technician', 'is_released'], name='billq_tech_release_idx'), models.Index(fields=['technician', 'queue_position'], name='billq_tech_pos_idx')],
                'constraints': [models.UniqueConstraint(fields=('technician', 'queue_position'), name='uniq_billing_queue_position_per_technician')],
            },
        ),
        migrations.CreateModel(
            name='BillingWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='operaciones.sesionbillingtecnico')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('started_at', 'id'),
                'indexes': [models.Index(fields=['technician', 'ended_at'], name='billwork_tech_end_idx'), models.Index(fields=['assignment', 'started_at'], name='billwork_asg_start_idx')],
            },
        ),
    ]
