# Generated by Django 5.2.1 on 2026-09-08 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0047_billingassignmentqueue_billingworksession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billingworksession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('technician',), name='uniq_open_billing_timer_per_technician'),
        ),
    ]
