# Generated by Django 5.2.1 on 2026-09-08 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0048_billingworksession_uniq_open_billing_timer_per_technician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionbilling',
            name='queue_priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Global execution sequence for this Billing/project. NULL means the project is outside the managed sequence.', null=True, unique=True, verbose_name='Work sequence priority'),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='queue_shown_now_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the latest manual Show Now action. Show Now removes the project from the managed priority sequence and makes it visible immediately.', null=True, verbose_name='Shown now at'),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='queue_shown_now_by',
            field=models.ForeignKey(blank=True, help_text='User who manually used Show Now for this Billing/project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_projects_shown_now', to=settings.AUTH_USER_MODEL, verbose_name='Shown now by'),
        ),
        migrations.AddField(
            model_name='sesionbilling',
            name='queue_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls whether this Billing/project may currently be shown to its assigned technicians. Visibility is independent from priority and timer state.', verbose_name='Visible to technicians'),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['queue_visible'], name='operaciones_queue_v_a6ce08_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionbilling',
            index=models.Index(fields=['queue_shown_now_at'], name='operaciones_queue_s_89d20d_idx'),
        ),
    ]
