# Generated by Django 5.2.1 on 2026-05-08 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(default='General', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Access permission',
                'verbose_name_plural': 'Access permissions',
                'ordering': ['module', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoleAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_index=True, max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access_control.accesspermission')),
            ],
            options={
                'verbose_name': 'Role access permission',
                'verbose_name_plural': 'Role access permissions',
                'ordering': ['permission__module', 'permission__order', 'role_name'],
                'unique_together': {('permission', 'role_name')},
            },
        ),
    ]
