# Generated by Django 5.2.1 on 2026-01-13 03:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_ft', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('end_ft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segment_length_ft', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('from_ft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_ft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='underground.route')),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('route', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_prev_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks_stages', to='underground.stage')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SegmentStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='underground.routesegment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='underground.stage')),
            ],
            options={
                'ordering': ('segment__index', 'stage__order'),
                'unique_together': {('segment', 'stage')},
            },
        ),
    ]
