# Generated by Django 5.2.1 on 2025-07-09 16:37

import cloudinary_storage.storage
import django.db.models.deletion
import logistica.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('guia', 'Guía de Despacho'), ('factura', 'Factura')], max_length=10)),
                ('numero_documento', models.CharField(max_length=50)),
                ('archivo_documento', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=logistica.models.ruta_ingreso_material, verbose_name='PDF de respaldo')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='logistica.bodega')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngresoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.ingresomaterial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.material')),
            ],
        ),
    ]
