# Generated by Django 5.2.1 on 2025-08-05 21:20

import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=utils.paths.upload_to, verbose_name='Archivo CAF (.xml)')),
                ('tipo_dte', models.PositiveIntegerField()),
                ('rango_inicio', models.PositiveIntegerField()),
                ('rango_fin', models.PositiveIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=utils.paths.upload_to, verbose_name='Archivo .pfx')),
                ('clave_certificado', models.CharField(max_length=255)),
                ('rut_emisor', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngresoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FolioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('guia', 'Guía de Despacho'), ('factura', 'Factura')], max_length=10)),
                ('numero_documento', models.CharField(max_length=50)),
                ('codigo_externo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código externo')),
                ('archivo_documento', models.FileField(upload_to=utils.paths.upload_to, verbose_name='PDF de respaldo')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitario ($)')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('id_proyecto', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('guia_despacho', 'Guía de Despacho')], max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to, verbose_name='XML firmado')),
                ('rut_receptor', models.CharField(max_length=15)),
                ('nombre_receptor', models.CharField(max_length=255)),
                ('giro_receptor', models.CharField(max_length=255)),
                ('direccion_receptor', models.CharField(max_length=255)),
                ('comuna_receptor', models.CharField(max_length=100)),
                ('ciudad_receptor', models.CharField(max_length=100)),
                ('fecha_emisión', models.DateField(auto_now_add=True)),
                ('obra', models.CharField(max_length=255)),
                ('chofer', models.CharField(max_length=255)),
                ('rut_transportista', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('estado_envio_sii', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('mensaje_sii', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
