# Generated by Django 5.2.1 on 2025-08-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocaf',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificadodigital',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foliodisponible',
            name='caf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.archivocaf'),
        ),
        migrations.AddField(
            model_name='ingresomaterial',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='logistica.bodega'),
        ),
        migrations.AddField(
            model_name='ingresomaterial',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleingresomaterial',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.ingresomaterial'),
        ),
        migrations.AddField(
            model_name='material',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.bodega'),
        ),
        migrations.AddField(
            model_name='detallesalidamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.material'),
        ),
        migrations.AddField(
            model_name='detalleingresomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.material'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.bodega'),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitido_salidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='entregado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregado_salidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallesalidamaterial',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.salidamaterial'),
        ),
        migrations.AlterUniqueTogether(
            name='foliodisponible',
            unique_together={('folio', 'caf')},
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('codigo_interno', 'bodega'), name='unique_codigo_interno_por_bodega'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('codigo_externo', 'bodega'), name='unique_codigo_externo_por_bodega'),
        ),
    ]
