# Generated by Django 5.2.1 on 2025-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresomaterial',
            name='codigo_externo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código externo'),
        ),
    ]
