# Generated by Django 5.2.1 on 2026-05-14 19:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import logistica.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['nombre'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='bodega',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodega',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit value ($)'),
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('serial', models.CharField(max_length=120, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Available quantity for this tool/equipment.')),
                ('valor_comercial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('foto', models.ImageField(blank=True, max_length=1024, null=True, upload_to=logistica.models.upload_to_herramienta_foto, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('operativa', 'Operational'), ('asignada', 'Assigned'), ('danada', 'Damaged'), ('extraviada', 'Lost'), ('robada', 'Stolen'), ('bodega', 'In warehouse')], default='operativa', max_length=20)),
                ('status_justificacion', models.TextField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_required', models.BooleanField(default=False, help_text='If enabled, the user must submit an inventory photo.')),
                ('next_inventory_due', models.DateField(blank=True, null=True)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='logistica.bodega')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_creadas', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_status_cambiado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HerramientaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_entregada', models.PositiveIntegerField(default=1)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cantidad_devuelta', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario_cierre', models.TextField(blank=True, null=True)),
                ('justificacion_diferencia', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pending'), ('aceptada', 'Accepted'), ('rechazada', 'Rejected'), ('terminada', 'Closed')], default='pendiente', max_length=20)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('aceptado_at', models.DateTimeField(blank=True, null=True)),
                ('rechazado_at', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herramientas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignadas_por', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignaciones_cerradas_por', to=settings.AUTH_USER_MODEL)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='logistica.herramienta')),
            ],
            options={
                'verbose_name': 'Tool assignment',
                'verbose_name_plural': 'Tool assignments',
                'ordering': ['-asignado_at'],
            },
        ),
        migrations.CreateModel(
            name='HerramientaAsignacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('close', 'Closed'), ('reset', 'Reset'), ('delete', 'Deleted'), ('inventario_solicitado', 'Inventory requested')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('nota', models.TextField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logistica.herramientaasignacion')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignaciones_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HerramientaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(max_length=1024, upload_to=logistica.models.upload_to_herramienta_inventario, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pending'), ('aprobado', 'Approved'), ('rechazado', 'Rejected')], default='pendiente', max_length=20)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='logistica.herramientaasignacion')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='logistica.herramienta')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool inventory',
                'verbose_name_plural': 'Tool inventories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['status'], name='logistica_h_status_6ab219_idx'),
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['serial'], name='logistica_h_serial_bdf1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacion',
            index=models.Index(fields=['active', 'estado'], name='logistica_h_active_c4c22c_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacion',
            index=models.Index(fields=['asignado_a', 'active'], name='logistica_h_asignad_4cf341_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacion',
            index=models.Index(fields=['herramienta', 'active'], name='logistica_h_herrami_e8d35a_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacionlog',
            index=models.Index(fields=['accion', 'created_at'], name='logistica_h_accion_533b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacionlog',
            index=models.Index(fields=['asignacion', 'created_at'], name='logistica_h_asignac_b0376e_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientainventario',
            index=models.Index(fields=['estado'], name='logistica_h_estado_8ca783_idx'),
        ),
    ]
