# Generated by Django 5.2.1 on 2025-07-09 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_ingresomaterial_codigo_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.IntegerField(choices=[(52, 'Guía de despacho')])),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='caf/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('rango_inicio', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FolioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('caf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.archivocaf')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('id_proyecto', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('guia', 'Guía de Despacho'), ('factura', 'Factura'), ('otro', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='salidas_materiales/')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.bodega')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitido_salidas', to=settings.AUTH_USER_MODEL)),
                ('entregado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregado_salidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.material')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.salidamaterial')),
            ],
        ),
    ]
