# Generated by Django 5.2.1 on 2025-07-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_archivocaf_foliodisponible_salidamaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foliodisponible',
            name='folio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='tipo_documento',
            field=models.CharField(choices=[('guia', 'Guía de Despacho'), ('factura', 'Factura'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='foliodisponible',
            unique_together={('folio', 'caf')},
        ),
    ]
