# Generated by Django 5.2.1 on 2025-07-10 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_alter_foliodisponible_folio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocaf',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivocaf',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='archivocaf',
            name='rango_fin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archivocaf',
            name='rango_inicio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='archivocaf',
            name='tipo_dte',
            field=models.PositiveIntegerField(),
        ),
    ]
