# Generated by Django 5.2.1 on 2025-07-10 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_archivocaf_usuario_alter_archivocaf_fecha_subida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/CertificadosDigitales/')),
                ('clave_certificado', models.CharField(max_length=255)),
                ('rut_emisor', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
