# Generated by Django 5.2.1 on 2025-07-10 14:45

import cloudinary_storage.storage
import logistica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_salidamaterial_chofer_salidamaterial_ciudad_receptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocaf',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=logistica.models.ruta_caf, verbose_name='Archivo CAF (.xml)'),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=logistica.models.ruta_certificado, verbose_name='Archivo .pfx'),
        ),
    ]
