# Generated by Django 5.2.1 on 2025-07-10 21:17

import cloudinary_storage.storage
import logistica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_alter_archivocaf_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamaterial',
            name='estado_envio_sii',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='salidamaterial',
            name='mensaje_sii',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=logistica.models.ruta_salida_material),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='tipo_documento',
            field=models.CharField(choices=[('guia_despacho', 'Guía de Despacho')], max_length=20),
        ),
    ]
