# Generated by Django 5.2.1 on 2025-07-11 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_salidamaterial_rut_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamaterial',
            name='fecha_emisión',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
