# Generated by Django 5.2.1 on 2025-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_salidamaterial_fecha_emisión'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitario ($)'),
        ),
    ]
