# Generated by Django 5.2.1 on 2025-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_alter_material_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesalidamaterial',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detallesalidamaterial',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallesalidamaterial',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
