# Generated by Django 5.2.1 on 2025-05-18 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='total_pago',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='telefono',
        ),
        migrations.AddField(
            model_name='produccion',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('en_ejecucion', 'En ejecución'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('liquidacion', 'Liquidación')], max_length=50),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='tecnicos.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CursoPrevencion',
        ),
    ]
