# Generated by Django 5.2.1 on 2025-05-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_remove_documento_fecha_subida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(default='Curso por defecto', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones', to='tecnicos.supervisor'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='tecnicos.tecnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccion',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
