# Generated by Django 5.2.1 on 2025-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_remove_curso_fecha_inicio_remove_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
