# Generated by Django 5.2.1 on 2025-05-23 04:54

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_tecnico_firma_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='firmas/'),
        ),
    ]
