# Generated by Django 5.2.1 on 2026-07-10 01:59

import django.db.models.deletion
import plan_reader.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanReaderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(upload_to=plan_reader.models.plan_reader_pdf_upload_path)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('co', models.CharField(blank=True, max_length=50, verbose_name='CO')),
                ('dfn', models.CharField(blank=True, max_length=50, verbose_name='DFN')),
                ('office', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('needs_review', 'Needs review'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('processed_pages', models.PositiveIntegerField(default=0)),
                ('failed_pages', models.PositiveIntegerField(default=0)),
                ('generated_excel', models.FileField(blank=True, null=True, upload_to=plan_reader.models.plan_reader_excel_upload_path)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_reader_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Reader Job',
                'verbose_name_plural': 'Plan Reader Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanReaderPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('sheet_name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('extracted_json', models.JSONField(blank=True, null=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='plan_reader.planreaderjob')),
            ],
            options={
                'verbose_name': 'Plan Reader Page',
                'verbose_name_plural': 'Plan Reader Pages',
                'ordering': ['job_id', 'page_number'],
                'unique_together': {('job', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='PlanReaderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(blank=True, max_length=50)),
                ('co', models.CharField(blank=True, max_length=50, verbose_name='CO')),
                ('dfn', models.CharField(blank=True, max_length=50, verbose_name='DFN')),
                ('project_name', models.CharField(blank=True, max_length=120)),
                ('primary_feed', models.CharField(blank=True, max_length=120)),
                ('visible_type', models.CharField(blank=True, max_length=120)),
                ('detected_box_type', models.CharField(blank=True, max_length=120)),
                ('has_p', models.BooleanField(default=False)),
                ('s_splitter', models.CharField(blank=True, max_length=50)),
                ('t_splitter', models.CharField(blank=True, max_length=50)),
                ('splice_count', models.PositiveIntegerField(default=0)),
                ('calculated_box_type', models.CharField(blank=True, max_length=120)),
                ('c108_ug', models.PositiveIntegerField(default=0)),
                ('c109_splices', models.PositiveIntegerField(default=0)),
                ('c110_splitters', models.PositiveIntegerField(default=0)),
                ('observation', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plan_reader.planreaderjob')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='plan_reader.planreaderpage')),
            ],
            options={
                'verbose_name': 'Plan Reader Item',
                'verbose_name_plural': 'Plan Reader Items',
                'ordering': ['sheet', 'project_name', 'primary_feed'],
            },
        ),
    ]
