# Generated by Django 5.2.1 on 2026-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planreaderjob',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planreaderjob',
            name='project',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
