# Generated by Django 5.2.1 on 2026-07-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_reader', '0002_planreaderjob_city_planreaderjob_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='planreaderitem',
            name='splitter_lines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
