# Generated by Django 5.2.1 on 2026-07-20 20:47

import django.db.models.deletion
import plan_reader.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_reader', '0004_remove_legacy_reading_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Internal stable identifier used by the Material Request builder.', max_length=120, unique=True)),
                ('material_type', models.CharField(blank=True, max_length=120, verbose_name='Type')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('material_name', models.CharField(max_length=500, verbose_name='Material')),
                ('uom', models.CharField(blank=True, default='EA', max_length=30, verbose_name='UOM')),
                ('auto_rule', models.CharField(choices=[('manual', 'Manual'), ('splice_case_a4', 'Splice case — A4'), ('splice_case_b8g_empty', 'Splice case — B8G without splitter'), ('splice_case_b8g_1x2', 'Splice case — B8G with 1x2'), ('splice_case_b8g_1x4', 'Splice case — B8G with 1x4'), ('splice_case_b8g_1x8', 'Splice case — B8G with 1x8'), ('splice_case_c12', 'Splice case — C12'), ('splitter_1x2', 'Splitter — 1x2'), ('splitter_1x4', 'Splitter — 1x4'), ('splitter_1x6', 'Splitter — 1x6'), ('splitter_1x8', 'Splitter — 1x8'), ('splice_sleeve_40mm', 'Splice sleeve — 40MM'), ('splice_sleeve_60mm', 'Splice sleeve — 60MM')], db_index=True, default='manual', max_length=60)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Catalog Item',
                'verbose_name_plural': 'Material Catalog Items',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='pr_matcat_active_order_idx'), models.Index(fields=['auto_rule', 'is_active'], name='pr_matcat_rule_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanReaderMaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'PDF generated')], db_index=True, default='draft', max_length=30)),
                ('subcontractor', models.CharField(blank=True, default='Hyperlink Networks LLC', max_length=255)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('market', models.CharField(blank=True, max_length=120)),
                ('dfn', models.CharField(blank=True, max_length=120, verbose_name='DFN')),
                ('contractor_employee_name', models.CharField(blank=True, max_length=255)),
                ('contractor_employee_signature', models.CharField(blank=True, help_text='Typed signature or employee name to display in the generated PDF.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to=plan_reader.models.plan_reader_material_request_pdf_upload_path)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plan_reader_material_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_request', to='plan_reader.planreaderjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_plan_reader_material_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Reader Material Request',
                'verbose_name_plural': 'Plan Reader Material Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanReaderMaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(blank=True, max_length=120, verbose_name='Type')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('material_name', models.CharField(max_length=500, verbose_name='Material')),
                ('uom', models.CharField(blank=True, default='EA', max_length=30, verbose_name='UOM')),
                ('quantity_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='QTY Requested')),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='QTY Received')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('automatic_edited', 'Automatic — edited by user')], db_index=True, default='manual', max_length=30)),
                ('auto_rule', models.CharField(choices=[('manual', 'Manual'), ('splice_case_a4', 'Splice case — A4'), ('splice_case_b8g_empty', 'Splice case — B8G without splitter'), ('splice_case_b8g_1x2', 'Splice case — B8G with 1x2'), ('splice_case_b8g_1x4', 'Splice case — B8G with 1x4'), ('splice_case_b8g_1x8', 'Splice case — B8G with 1x8'), ('splice_case_c12', 'Splice case — C12'), ('splitter_1x2', 'Splitter — 1x2'), ('splitter_1x4', 'Splitter — 1x4'), ('splitter_1x6', 'Splitter — 1x6'), ('splitter_1x8', 'Splitter — 1x8'), ('splice_sleeve_40mm', 'Splice sleeve — 40MM'), ('splice_sleeve_60mm', 'Splice sleeve — 60MM')], db_index=True, default='manual', max_length=60)),
                ('automatic_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Last quantity calculated automatically from Plan Reader.', max_digits=14)),
                ('calculation_note', models.TextField(blank=True, help_text='Explanation of how the automatic quantity was calculated.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_request_items', to='plan_reader.materialcatalogitem')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plan_reader.planreadermaterialrequest')),
            ],
            options={
                'verbose_name': 'Plan Reader Material Request Item',
                'verbose_name_plural': 'Plan Reader Material Request Items',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['material_request', 'display_order'], name='pr_matreq_item_order_idx'), models.Index(fields=['material_request', 'source'], name='pr_matreq_item_source_idx'), models.Index(fields=['material_request', 'auto_rule'], name='pr_matreq_item_rule_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('catalog_item__isnull', False)), fields=('material_request', 'catalog_item'), name='unique_catalog_item_per_material_request')],
            },
        ),
    ]
