# Generated by Django 5.2.1 on 2026-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_reader', '0005_materialcatalogitem_planreadermaterialrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcatalogitem',
            name='auto_rule',
            field=models.CharField(choices=[('manual', 'Manual'), ('splice_case_a4', 'Splice case — A4'), ('splice_case_b8g_empty', 'Splice case — B8G without splitter'), ('splice_case_b8g_1x2', 'Splice case — B8G with 1x2'), ('splice_case_b8g_1x4', 'Splice case — B8G with 1x4'), ('splice_case_b8g_1x8', 'Splice case — B8G with 1x8'), ('splice_case_c12', 'Splice case — C12'), ('tds_label_a4', 'TDS Label — A4'), ('tds_label_b8g_empty', 'TDS Label — B8G without splitter'), ('tds_label_b8g_1x2', 'TDS Label — B8G with 1x2'), ('tds_label_b8g_1x4', 'TDS Label — B8G with 1x4'), ('tds_label_b8g_1x8', 'TDS Label — B8G with 1x8'), ('tds_label_c12', 'TDS Label — C12'), ('splitter_1x2', 'Splitter without connectors — 1x2'), ('splitter_1x4', 'Splitter without connectors — 1x4'), ('splitter_1x6', 'Splitter without connectors — 1x6'), ('splitter_1x8', 'Splitter without connectors — 1x8'), ('splice_sleeve_40mm', 'Splice sleeve — 40MM'), ('splice_sleeve_60mm', 'Splice sleeve — 60MM')], db_index=True, default='manual', max_length=60),
        ),
        migrations.AlterField(
            model_name='planreadermaterialrequestitem',
            name='auto_rule',
            field=models.CharField(choices=[('manual', 'Manual'), ('splice_case_a4', 'Splice case — A4'), ('splice_case_b8g_empty', 'Splice case — B8G without splitter'), ('splice_case_b8g_1x2', 'Splice case — B8G with 1x2'), ('splice_case_b8g_1x4', 'Splice case — B8G with 1x4'), ('splice_case_b8g_1x8', 'Splice case — B8G with 1x8'), ('splice_case_c12', 'Splice case — C12'), ('tds_label_a4', 'TDS Label — A4'), ('tds_label_b8g_empty', 'TDS Label — B8G without splitter'), ('tds_label_b8g_1x2', 'TDS Label — B8G with 1x2'), ('tds_label_b8g_1x4', 'TDS Label — B8G with 1x4'), ('tds_label_b8g_1x8', 'TDS Label — B8G with 1x8'), ('tds_label_c12', 'TDS Label — C12'), ('splitter_1x2', 'Splitter without connectors — 1x2'), ('splitter_1x4', 'Splitter without connectors — 1x4'), ('splitter_1x6', 'Splitter without connectors — 1x6'), ('splitter_1x8', 'Splitter without connectors — 1x8'), ('splice_sleeve_40mm', 'Splice sleeve — 40MM'), ('splice_sleeve_60mm', 'Splice sleeve — 60MM')], db_index=True, default='manual', max_length=60),
        ),
    ]
