# Generated by Django 5.2.1 on 2026-07-20 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_reader', '0006_alter_materialcatalogitem_auto_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planreadermaterialrequest',
            name='request_type',
            field=models.CharField(choices=[('splicing', 'Splicing'), ('cable', 'Cable')], db_index=True, default='splicing', max_length=30),
        ),
        migrations.AlterField(
            model_name='planreadermaterialrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='plan_reader.planreaderjob'),
        ),
        migrations.AddIndex(
            model_name='planreadermaterialrequest',
            index=models.Index(fields=['job', 'request_type'], name='pr_matreq_job_type_idx'),
        ),
        migrations.AddIndex(
            model_name='planreadermaterialrequest',
            index=models.Index(fields=['request_type', 'status'], name='pr_matreq_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='planreadermaterialrequest',
            constraint=models.UniqueConstraint(fields=('job', 'request_type'), name='unique_material_request_type_per_job'),
        ),
    ]
