# Generated by Django 5.2.1 on 2026-04-10 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0031_sesionbilling_tech_payment_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CableInstallationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_code', models.CharField(max_length=100)),
                ('camera_number', models.CharField(max_length=100)),
                ('cable_type_planned', models.CharField(choices=[('48FO', '48FO'), ('64FO', '64FO')], max_length=10)),
                ('cable_type_installed', models.CharField(blank=True, choices=[('48FO', '48FO'), ('64FO', '64FO')], default='', max_length=10)),
                ('reserve_ft_planned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reserve_ft_installed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_measure_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_measure_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_end_measure_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installed_length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('technician_note', models.TextField(blank=True, default='')),
                ('supervisor_note', models.TextField(blank=True, default='')),
                ('warning_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('improve', 'Improve')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_requirements_assigned', to=settings.AUTH_USER_MODEL)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_requirements', to='operaciones.sesionbilling')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_requirements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('billing', 'pk_code')},
            },
        ),
        migrations.CreateModel(
            name='CableInstallationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('start_cable_photo', 'Start cable photo'), ('end_cable_photo', 'End cable photo'), ('camera_photo', 'Camera/handhold photo')], max_length=30)),
                ('image', models.ImageField(upload_to='operaciones/cable_installation/')),
                ('note', models.TextField(blank=True, default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gps_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_evidences_created', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cable_installation.cableinstallationrequirement')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('requirement', 'evidence_type')},
            },
        ),
    ]
