# Generated by Django 5.2.1 on 2026-04-10 04:34

import cable_installation.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_installation', '0001_initial'),
        ('operaciones', '0032_sesionbilling_is_cable_installation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cableinstallationrequirement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cableinstallationrequirement',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='cableinstallationrequirement',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='cableinstallationrequirement',
            name='created_by',
        ),
        migrations.CreateModel(
            name='CableAssignmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('end_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('installed_ft', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_end_ft_low', models.DecimalField(blank=True, decimal_places=2, help_text='start_ft - planned_reserve_ft snapshot', max_digits=12, null=True)),
                ('expected_end_ft_high', models.DecimalField(blank=True, decimal_places=2, help_text='start_ft + planned_reserve_ft snapshot', max_digits=12, null=True)),
                ('end_ft_overridden', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('retake', 'Retake required'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('supervisor_note', models.TextField(blank=True, default='')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_assignment_requirements', to='operaciones.sesionbillingtecnico')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_requirements_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('requirement__order', 'requirement__sequence_no', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CableEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=1024, storage=storages.backends.s3.S3Storage(), upload_to=cable_installation.models.upload_to_cable_evidence, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cable_installation.cableassignmentrequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_evidences_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CableRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(help_text='Sequential identifier inside the billing.', validators=[django.core.validators.MinValueValidator(1)])),
                ('handhole', models.CharField(max_length=120)),
                ('planned_reserve_ft', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('warning', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_requirements', to='operaciones.sesionbilling')),
            ],
            options={
                'ordering': ('order', 'sequence_no', 'id'),
            },
        ),
        migrations.AddField(
            model_name='cableassignmentrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rows', to='cable_installation.cablerequirement'),
        ),
        migrations.DeleteModel(
            name='CableInstallationEvidence',
        ),
        migrations.DeleteModel(
            name='CableInstallationRequirement',
        ),
        migrations.AddIndex(
            model_name='cableevidence',
            index=models.Index(fields=['assignment_requirement', 'review_status'], name='cable_insta_assignm_0276f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cablerequirement',
            index=models.Index(fields=['billing', 'order'], name='cable_insta_billing_94747c_idx'),
        ),
        migrations.AddIndex(
            model_name='cablerequirement',
            index=models.Index(fields=['billing', 'sequence_no'], name='cable_insta_billing_7c4b7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cablerequirement',
            constraint=models.UniqueConstraint(fields=('billing', 'sequence_no'), name='uniq_cable_requirement_sequence_per_billing'),
        ),
        migrations.AddIndex(
            model_name='cableassignmentrequirement',
            index=models.Index(fields=['assignment', 'status'], name='cable_insta_assignm_c7b2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='cableassignmentrequirement',
            index=models.Index(fields=['requirement', 'status'], name='cable_insta_require_c775f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cableassignmentrequirement',
            constraint=models.UniqueConstraint(fields=('assignment', 'requirement'), name='uniq_cable_assignment_requirement'),
        ),
    ]
