# Generated by Django 5.2.1 on 2026-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_installation', '0002_alter_cableinstallationrequirement_unique_together_and_more'),
        ('operaciones', '0032_sesionbilling_is_cable_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablerequirement',
            name='required',
            field=models.BooleanField(db_index=True, default=True, help_text='If enabled, technician must complete this requirement.'),
        ),
        migrations.AddIndex(
            model_name='cablerequirement',
            index=models.Index(fields=['billing', 'required'], name='cable_insta_billing_fd5b75_idx'),
        ),
    ]
