# Generated by Django 5.2.1 on 2026-04-10 16:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_installation', '0003_cablerequirement_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablerequirement',
            name='end_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cablerequirement',
            name='end_ft_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cablerequirement',
            name='expected_end_ft_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cablerequirement',
            name='expected_end_ft_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cablerequirement',
            name='installed_ft',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cablerequirement',
            name='start_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cableassignmentrequirement',
            name='expected_end_ft_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cableassignmentrequirement',
            name='expected_end_ft_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
