# Generated by Django 5.2.1 on 2026-04-10 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable_installation', '0004_cablerequirement_end_ft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cableevidence',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('start_cable', 'Start cable'), ('end_cable', 'End cable'), ('handhole', 'Handhole')], db_index=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cableevidence',
            index=models.Index(fields=['assignment_requirement', 'shot_type'], name='cable_insta_assignm_bc5887_idx'),
        ),
    ]
