# Generated by Django 5.2.1 on 2026-01-09 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronDailyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('run_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('ok', models.BooleanField(default=True)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-run_date', '-id'),
                'constraints': [models.UniqueConstraint(fields=('name', 'run_date'), name='uniq_cron_name_date')],
            },
        ),
    ]
