# Generated by Django 5.2.1 on 2025-06-09 22:26

import django.db.models.deletion
import liquidaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('año', models.PositiveIntegerField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivo_pdf_liquidacion', models.FileField(blank=True, null=True, upload_to=liquidaciones.models.ruta_archivo_sin_firmar, verbose_name='Liquidación de Sueldo')),
                ('pdf_firmado', models.FileField(blank=True, null=True, upload_to=liquidaciones.models.ruta_archivo_firmado, verbose_name='Liquidación de sueldo firmada')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firmada', models.BooleanField(default=False)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'constraints': [models.UniqueConstraint(fields=('tecnico', 'mes', 'año'), name='unique_liquidacion_por_tecnico_mes_anio', violation_error_message='Ya existe una liquidación para este técnico en ese mes y año.')],
            },
        ),
    ]
