# Generated by Django 5.2.1 on 2025-06-04 16:50

import django.core.files.storage
import liquidaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('año', models.PositiveIntegerField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivo_pdf_liquidacion', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=liquidaciones.models.ruta_archivo_sin_firmar, verbose_name='Liquidación de Sueldo')),
                ('pdf_firmado', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=liquidaciones.models.ruta_archivo_firmado, verbose_name='Liquidación de sueldo firmada')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firmada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
    ]
