# Generated by Django 5.2.1 on 2025-08-05 21:35

import utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('año', models.PositiveIntegerField()),
                ('archivo_pdf_liquidacion', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to, verbose_name='Liquidación de Sueldo')),
                ('pdf_firmado', models.FileField(blank=True, null=True, upload_to=utils.paths.upload_to, verbose_name='Liquidación de sueldo firmada')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firmada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
    ]
