# Generated by Django 5.2.1 on 2025-08-05 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquidaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(fields=('tecnico', 'mes', 'año'), name='unique_liquidacion_por_tecnico_mes_anio', violation_error_message='Ya existe una liquidación para este técnico en ese mes y año.'),
        ),
    ]
