# Generated by Django 5.2.1 on 2025-05-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='archivo_pdf',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='año',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='mes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, upload_to='pdf_firmados/'),
        ),
    ]
