# Generated by Django 5.2.1 on 2025-06-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_alter_liquidacion_archivo_pdf_liquidacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacion',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='liquidacion',
            name='unique_liquidacion_por_tecnico_mes_anio',
        ),
    ]
