# Generated by Django 5.2.1 on 2025-05-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_remove_liquidacion_archivo_pdf_liquidacion_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='archivo_pdf_liquidacion',
            field=models.FileField(blank=True, null=True, upload_to='pdf_originales/', verbose_name='Liquidación de sueldo'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, upload_to='pdf_firmados/', verbose_name='Liquidación de sueldo firmada'),
        ),
    ]
