# Generated by Django 5.2.1 on 2025-06-07 00:33

import liquidaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0003_alter_liquidacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='archivo_pdf_liquidacion',
            field=models.FileField(blank=True, null=True, upload_to=liquidaciones.models.ruta_archivo_sin_firmar, verbose_name='Liquidación de Sueldo'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, upload_to=liquidaciones.models.ruta_archivo_firmado, verbose_name='Liquidación de sueldo firmada'),
        ),
    ]
