# Generated by Django 5.2.1 on 2025-06-25 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0003_alter_liquidacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacion',
            options={'verbose_name': 'Liquidación', 'verbose_name_plural': 'Liquidaciones'},
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(fields=('tecnico', 'mes', 'año'), name='unique_liquidacion_por_tecnico_mes_anio', violation_error_message='Ya existe una liquidación para este técnico en ese mes y año.'),
        ),
    ]
