# Generated by Django 5.2.1 on 2025-05-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0004_alter_liquidacion_archivo_pdf_liquidacion_and_more'),
        ('tecnicos', '0005_alter_tecnico_firma_digital'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('tecnico', 'mes', 'año')},
        ),
    ]
