# Generated by Django 5.2.1 on 2025-06-08 01:01

import django.core.files.storage
import liquidaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0004_alter_liquidacion_archivo_pdf_liquidacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='archivo_pdf_liquidacion',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=liquidaciones.models.ruta_archivo_sin_firmar, verbose_name='Liquidación de Sueldo'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=liquidaciones.models.ruta_archivo_firmado, verbose_name='Liquidación de sueldo firmada'),
        ),
    ]
